### ISSUE TITLE
Refreshing after navigating via react-router results in a 500

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#1]
To reproduce, navigate to the root of the UI, click any icon, then refresh.

This is probably a regression that wasn't caught when the project was upgraded to .NET 5.0; there's a catch-all middleware that is supposed to handle these and it apparently is no longer.

Middleware in question:

```c#
            // if we made it this far and the route still wasn't matched, return the index
            // this is required so that SPA routing (React Router, etc) can work properly
            app.Use(async (context, next) =>
            {
                // exclude API routes which are not matched or return a 404
                if (!context.Request.Path.StartsWithSegments("/api"))
                {
                    context.Request.Path = "/";
                }

                await next();
            });
```

**Comment by jpdillingham** [comment]
The root cause was missing XML documentation in publish output.  Swagger middleware comes before the middleware shared above, and when running it will throw if it can't find it.

I'll log a separate issue to detect the XML file alongside the executable and skip binding of the Swagger middleware if it isn't present.  Deleting this file shouldn't cause the webserver to throw.

**Comment by snapetech** [comment]
✅ **Implemented and deployed**

**Backend:**
- Added WishlistService with background processing
- Created WishlistDbContext with SQLite storage
- Implemented API endpoints: GET, POST, PUT, DELETE, and manual trigger
- Added configuration options via CLI and environment variables

**Frontend:**
- Created Wishlist page with full CRUD UI
- Added navigation menu item
- Integrated with search API for automatic background searches
- Support for filters, max results, auto-download toggle

**Testing:**
- Backend running on port 5099
- Frontend running on port 3099
- Database automatically created on startup
- All CRUD operations verified working

Ready for production use!
