### ISSUE TITLE
Add the ability to set unix file permissions after download

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#1028]
### Discussed in https://github.com/slskd/slskd/discussions/1014

<div type='discussions-op-text'>

<sup>Originally posted by **quaintyurt** December 11, 2023</sup>
I'm running in a Docker container on unRaid. All of the downloaded files and folders are set with permission `-rw-r-r--`. Is there a setting within the config that changes the default to 777 or to set UMASK? </div>

**Comment by kinnikinnick** [comment]
same issue.. nothing has changed yet with this yes?  I'm guessing I'll just have to set the user to share a uid with any other docker apps that need write access to slsk files :/

**Comment by S7ewie** [comment]
Same issue. You can run the "New Permissions" tool in Unraid but would be much better if slskd would set the permission.

**Comment by NyxHemera** [comment]
New Permissions tool does fix it but yeah this is pretty annoying. Most containers like sonarr and lidarr do this through a UMASK variable.

**Comment by NyxHemera** [comment]
Ok I'm not super familiar with .net or C# code, but I think I found the issue and what would need to be changed. Currently in DownloadService.cs within [GetLocalFileStream](https://github.com/slskd/slskd/blob/37dea1f91371900dcfb4fae8f46c6f3a6dc98126/src/slskd/Transfers/Downloads/DownloadService.cs#L601C20-L601C34), a new FileStream is instantiated without passing the parameter for [FileAccess](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileaccess?view=net-8.0). [FileStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=net-8.0#system-io-filestream-ctor(system-string-system-io-filemode-system-io-fileaccess)) does allow for an overload with this parameter. I'm pretty sure this could just pass a environment variable and accomplish what needs done.

It could be that when the file is transferred from incomplete to complete that the permissions are changed there or could be instead, but I haven't had a chance to dive in to that. 

@jpdillingham Hope this helps. I'm not super familiar with C# so I don't think I can make these changes myself but if I get some free time I might try and make a PR.

**Comment by jpdillingham** [comment]
Glad to see interest here, it's what helps me figure out what to work on next.  The UMASK comment is especially helpful, I'll go take a look at how the *arr apps implement this (they are also .NET based, lucky for me!) and will tackle this next.

**Comment by jpdillingham** [comment]
I've done a bunch of digging in the past couple hours and I'll share my findings here so maybe someone will correct me if I'm misunderstanding.

The UMASK offered by the *arr applications is, like PUID and GUID, a linuxserver construct.  I have tried and failed to dig through their Dockerfiles to see exactly how that is applied, but the concept seems rather straightforward.

UMASK refers to the unix utility [umask](https://en.wikipedia.org/wiki/Umask); this is what controls the permissions of files that a process creates.  On my system (vanilla Ubuntu) my terminal has a default umask of 0002, and any new file I create gets permissions `rw-rw-r--`.  If I change umask to 022 and create a different file, I get `rw-r--r--`, as seen here:

![Image](https://github.com/slskd/slskd/assets/17145758/6b389ee1-921a-488c-826a-b2b258c48235)

Doing some digging on the application side, I see .NET 7 introduced [SetUnixFileMode](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.setunixfilemode?view=net-8.0) which would allow me to explicitly set a file's permission after transfers are complete.  This would work only on unix-like OSes; I'd need an equivalent solution for Windows.  @NyxHemera I appreciate you digging into `FileStream`! The `FileAccess` specified when creating the stream applies only to the filesystem lock while the stream is open, it doesn't set any attributes.

Given all of this, it seems the options are:

1. Implement a `UMASK` environment variable in the Dockerfile and execute `umask $UMASK` prior to starting the application (need to test this)
2. Add logic to execute OS-specific commands to set file attributes after downloads are complete, along with new options to allow users to specify the permissions they'd like along with the rest of the config

I think I'll start with #1 and then see if anyone would like to have #2.  The UMASK option seems a little hostile to casual users but it should be quick to implement.

Would love to hear opinions on this!

**Comment by jpdillingham** [comment]
I confirmed that executing `umask <whatever>` before starting the app works, but it will apply to any and all files created by the application, including the default configuration file.  I could easily see someone setting umask expecting downloaded files to be created with 777 permissions and inadvertently setting the same on the config file, which contains secrets.

With that in mind I'll take a look at option 2 instead.

**Comment by jpdillingham** [comment]
I'm going to be doing some final testing and then will release this feature.  

In short; setting `SLSKD_UMASK` will set the umask of the executable within the Docker container and should meet the needs of everyone using Docker.

For those that want more control over file permissions or that aren't using docker, there's a new setting that will give granular control over the mode, but this can't be set any higher than the application's `umask` so there might not be an incredible amount of value.
