### ISSUE TITLE
Docker Healthcheck failing

### ISSUE THREAD

**Issue by DarkSirrush** [slskd/slskd#1037]
Hello,

I was trying to get slsk setup with Traefik, however the healthcheck doesn't get past 'starting'. I notice there is an old issue ( #99) that was marked as fixed, with the same problem/reason it was noticed.

I can successfully download/upload/populate searches, and I don't see anything wrong in the logs.

This has been tried with both 0.19.5.0 (slskd/slskd:latest) and 0.19.5.65534 (slskd/slskd:canary).

Healthcheck:

`sudo docker inspect --format "{{json .State.Health }}" slskd`

 `{"Status":"starting","FailingStreak":1,"Log":[{"Start":"2024-01-02T12:01:03.925898875-08:00","End":"2024-01-02T12:01:04.064639199-08:00","ExitCode":5,"Output":""}]}`

**Comment by jpdillingham** [comment]
I can't reproduce.  Can you share your settings?

**Comment by DarkSirrush** [comment]
...Apparently I did not test settings I thought I had. It was :
```

  https:
    disabled: false
    port: 5031
    force: true
    certificate:
      pfx: ~
      password: ~
```
without linking the certificate. Which I thought I changed after discovering traefik was not working. It works fine with `force: false` and traefik providing the certificate/forcing https on that end.
