### ISSUE TITLE
Unnecessary numbers in downloaded filenames

### ISSUE THREAD

**Issue by o-laptiy** [slskd/slskd#1039]
Hello,
This is a minor problem that I've encountered and have already solved, but still wanted to put it out there just in case.

All the files I would download from anyone would end up having names like:
- 01 little dipper **_638392102386101541** .mp3
- 02 the pod **_638392103834735432** .mp3

etc. 
The weirdest thing is that the file had an expected name during downloading and only after it would download completely it got such "tag". 

Anyway, the problem was caused by either using the same folder for both incomplete and downloads or the name of the said folder: "/mnt/music/**!unsorted!**". After I separated those two folders and gave them the default name the problem has been fixed.

**Comment by jpdillingham** [comment]
This is desired behavior, added in #682, and it's inevitable if you use the same folder for incomplete and complete downloads.  I'll update the documentation to warn against this.

**Comment by o-laptiy** [comment]
Ah, sorry then. I've tried searching for this issue but didn't use the same wording apparently.
