### ISSUE TITLE
ban/ignore users in chat

### ISSUE THREAD

**Issue by davidzx** [slskd/slskd#1047]
lots of trolls in the chat rooms, would be nice to be able to ban/ignore them in chat so we don't have to see them anymore

**Comment by jpdillingham** [comment]
Thanks for raising this; it had been in the back of my mind but I haven't remembered to create an issue for it.

I'm trying to decide if this should be an extension of the 'blacklist' functionality, or something different.  I'm leaning heavily towards something different.  This would probably look like an extension of the `rooms` config to include a list of ignored usernames.

I'm also not sure if the same settings should apply to direct messages, too.  Probably not? I'll have to think about it some more.

**Comment by mathiascode** [comment]
> I'm also not sure if the same settings should apply to direct messages, too. Probably not? I'll have to think about it some more.

Nicotine+ has a global ignore system that rejects the following things from an ignored user:
- Private messages
- Chat messages
- Search results

IIRC, SoulseekQt works the same.

**Comment by samhatter** [comment]
This would be very helpful.

**Comment by jpdillingham** [comment]
Added in #1180.

I think there probably needs to be a way to "unshare" a user without blocking their messages, but I'll wait until someone asks for it to worry about it.
