### ISSUE TITLE
slskd browse other user and user shares unhandled exception

### ISSUE THREAD

**Issue by RLB2310** [slskd/slskd#1070]
I have setup slskd on my Raspberry Pi 4 Debian through docker  (Also tested on Arch Linux x64 PC) and I have successfully setup everything with working downloads. I can't however, view other user shares or my own. Here is the log file showing the issue:

> An unhanded exception has occurred while executing the request.: 
> Soulseek.SoulseekClientException: Failed to browse user ###: Failed to establish a direct or indirect message connection to ### (220.233.4#.##:50300) ---> Soulseek.ConnectionException: Failed to establish a direct or indirect message connection to ### (220.233.#.##:50300) at Soulseek.Network.PeerConnectionManager.<>c__DisplayClass39_0.<<GetOrAddMessageConnectionAsync>g__GetConnection|0>d.MoveNext() --- End of stack trace from previous location --- at Soulseek.Network.PeerConnectionManager.GetOrAddMessageConnectionAsync(ConnectToPeerResponse connectToPeerResponse) at Soulseek.SoulseekClient.BrowseInternalAsync(String username, BrowseOptions options, CancellationToken cancellationToken) --- End of inner exception stack trace --- at Soulseek.SoulseekClient.BrowseInternalAsync(String username, BrowseOptions options, CancellationToken cancellationToken) at slskd.Users.API.UsersController.Browse(String username) at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at slskd.HTMLInjectionMiddleware.InvokeAsync(HttpContext context) at slskd.HTMLRewriteMiddleware.InvokeAsync(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
> 

I have ensured that port 50300 is open as well as testing other ports changed in the configuration file. I have a working connection and can download files on both setups. I also can't view the configured shares on Nicotine+ or any Soulseek client:

debug: false
remoteConfiguration: true
remoteFileManagement: false
instanceName: default
flags:
  noLogo: false
  noStart: false
  noConnect: false
  noShareScan: false
  forceShareScan: false
  noVersionCheck: false
  logSQL: false
  experimental: false
  volatile: false
  caseSensitiveRegEx: false
relay:
  enabled: false
  mode: controller
  controller:
    address: null
    ignoreCertificateErrors: false
    apiKey: null
    secret: null
    downloads: false
  agents: {}
directories:
  incomplete: /var/lib/slskd/.local/share/slskd/incomplete
  downloads: /var/lib/slskd/.local/share/slskd/downloads
shares:
  directories:
    - /mnt/rpi/Music_sorted
  filters: []
  cache:
    storageMode: memory
    workers: 8
global:
  upload:
    slots: 10
    speedLimit: 2147483647
  download:
    slots: 2147483647
    speedLimit: 2147483647
groups:
  default:
    upload:
      priority: 1
      strategy: roundrobin
      slots: 2147483647
      speedLimit: 2147483647
  leechers:
    thresholds:
      files: 1
      directories: 1
    upload:
      priority: 1
      strategy: roundrobin
      slots: 2147483647
      speedLimit: 2147483647
  blacklisted:
    members: []
    cidrs: []
  userDefined: {}
filters:
  search:
    request: []
rooms: []
web:
  port: 5030
  https:
    disabled: false
    port: 5031
    force: false
    certificate:
      pfx: null
      password: null
  urlBase: /
  contentPath: wwwroot
  logging: false
  authentication:
    disabled: false
    username: ###
    password: "*****"
    jwt:
      key: "*****"
      ttl: 604800000
    apiKeys: {}
retention:
  transfers:
    upload:
      succeeded: null
      errored: null
      cancelled: null
    download:
      succeeded: null
      errored: null
      cancelled: null
  files:
    complete: null
    incomplete: null
  logs: 180
logger:
  loki: null
  disk: true
metrics:
  enabled: false
  url: /metrics
  authentication:
    disabled: false
    username: slskd
    password: "*****"
feature:
  swagger: false
soulseek:
  address: vps.slsknet.org
  port: 2271
  username: ###
  password: "*****"
  description: A slskd user. https://github.com/slskd/slskd
  listenIpAddress: 0.0.0.0
  listenPort: 50300
  diagnosticLevel: Info
  distributedNetwork:
    disabled: false
    disableChildren: false
    childLimit: 25
    logging: false
  connection:
    timeout:
      connect: 10000
      inactivity: 15000
    buffer:
      read: 16384
      write: 16384
      transfer: 262144
      writeQueue: 50
    proxy:
      enabled: false
      address: null
      port: null
      username: null
      password: null
integration:
  ftp:
    enabled: false
    address: null
    port: 21
    encryptionMode: auto
    ignoreCertificateErrors: false
    username: null
    password: null
    remotePath: /
    overwriteExisting: true
    connectionTimeout: 5000
    retryAttempts: 3
  pushbullet:
    enabled: false
    accessToken: null
    notificationPrefix: "From slskd:"
    notifyOnPrivateMessage: true
    notifyOnRoomMention: true
    retryAttempts: 3
    cooldownTime: 900000

**Comment by RLB2310** [comment]
Viewing other users seems to be working fine now. Maybe I'm misunderstanding this. Am I supposed to be able to view my own user?

**Comment by jpdillingham** [comment]
An inability to browse yourself indicates that port forwarding isn't set up properly, as it requires a round trip through your public IP.
