### ISSUE TITLE
Unable to upload to FTP server; connection times out every time.

### ISSUE THREAD

**Issue by sebbthepleb** [slskd/slskd#1072]
I have set up an FTP server in the configuration, and have spent about an hour trying to get a successful upload but none have come through, all timing out after 5000ms and not giving me any other error message.

```Failed to upload "filename" to FTP after 3 attempts: "One or more errors occurred. (Failed to connect to server after 5000ms) (Failed to connect to server after 5000ms) (Failed to connect to server after 5000ms)```

I am unsure as to why this is happening and i am wondering whether it could be a problem with my setup (which i have combed through and nothing looks wrong to me), or if this is an issue with slskd itself.

**Comment by jpdillingham** [comment]
I just verified with the latest canary release and it's working fine for me.  How are you running the application?  If you're using docker you might want to connect to the container interactively and make sure you can ping the server.

**Comment by sebbthepleb** [comment]
Just tried to connect to the same share on my laptop and found that it doesn't connect with either FTP or SMB, so it's got be something to do with my hosting rather than the container. Thanks for the suggestion though :)
