### ISSUE TITLE
Cannot login to UI 

### ISSUE THREAD

**Issue by caspargross** [slskd/slskd#1073]
Hi,

I have the slskd container running on a Yunohost instance. It is on a subdomain configured with the redirect. Basically it should work like a normal reverse proxy installation with nginx. I have disabled HTTPS in slskd since the subdomain enforces SSL with a redirect anyway. 

I can load the login page without problems. When I try to login with correct username and password i cannot open the session. I dont get visual 401 error that is shown with a wrong password. Here is the log of the requests. 
```
[slskd.Application] [21:30:13 INF] Logged in to the Soulseek server as ******
[slskd.Application] [21:30:13 INF] Version 0.19.5.0 is up to date.
[Serilog.AspNetCore.RequestLoggingMiddleware] [21:30:22 INF] HTTP GET /index.html responded 200 in 99.2081 ms
[Serilog.AspNetCore.RequestLoggingMiddleware] [21:30:22 INF] HTTP GET /api/v0/session/enabled responded 200 in 50.5017 ms
[Serilog.AspNetCore.RequestLoggingMiddleware] [21:30:22 INF] HTTP GET /api/v0/session responded 401 in 26.7708 ms
[Serilog.AspNetCore.RequestLoggingMiddleware] [21:30:33 INF] HTTP POST /api/v0/session responded 200 in 77.5231 ms
[Serilog.AspNetCore.RequestLoggingMiddleware] [21:30:33 INF] HTTP GET /api/v0/session/enabled responded 200 in 10.3989 ms
[Serilog.AspNetCore.RequestLoggingMiddleware] [21:30:33 INF] HTTP POST /hub/search/negotiate responded 401 in 11.2866 ms
[Serilog.AspNetCore.RequestLoggingMiddleware] [21:30:33 INF] HTTP GET /api/v0/session responded 401 in 10.3335 ms
````

The following screenshots show the state after trying to log in with correct username and password. 

![image](https://github.com/slskd/slskd/assets/10211013/ae5cc8a8-05de-4f08-81b5-39176411bd15)

Can you help me figure out whats wrong?
Thanks, Caspar

**Comment by jpdillingham** [comment]
The successful POST to `/session` indicates that the username and password were accepted.  Within that response you should find something like this:

```json
{
    "expires": 1707429057,
    "issued": 1706824257,
    "name": "<your username>",
    "notBefore": 1706824257,
    "token": "eyJhbGciOiJIUzI1.....<lots more>",
    "tokenType": "Bearer"
}
```
In the subsequent GET from `/session` you should see that the `Authorization` header is `Bearer <the token>`, like this:

![image](https://github.com/slskd/slskd/assets/17145758/87280f33-204c-463e-ab67-45bfa4fdafdd)

Can you confirm whether you're seeing that?

**Comment by jpdillingham** [comment]
I did some digging and found that this might be a known issue: https://forum.yunohost.org/t/unable-to-connect-in-some-containerized-app-if-logged-in-yunohost/26906

**Comment by caspargross** [comment]
Thanks for replying so fast!
Yes that was the problem. The solution in the link you found works for me. Many thanks!
