### ISSUE TITLE
Docker is requesting the wrong Image platform (arm64)

### ISSUE THREAD

**Issue by halpz** [slskd/slskd#1098]
I am getting this issue when trying to use docker compose:

I am trying to run on raspberry pi 4 (arm64) but it is trying to run the amd64 image

this must be a recent thing as this used to work previously

 ```
Network slskd_default  Creating
 Network slskd_default  Created
 Container slskd  Creating
 slskd The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
 Container slskd  Created
 Container slskd  Starting
 Container slskd  Started
```

**Comment by jpdillingham** [comment]
Try now.  I ran a build on Docker hub and it pushed an image to the latest tag while I wasn't paying attention.  The 0.20.1 release should fix it.

**Comment by halpz** [comment]
Thanks!
