### ISSUE TITLE
Add retry loop to initial connection attempt

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#1132]
Currently the `ConnectionWatchdog` is started upon client disconnect.  It works as designed to ensure the application reconnects automatically following a network issue.

This unfortunately doesn't work when the application is first starting and the server can't be reached.

This will be as simple as starting the connection watchdog instead of connecting directly; I've made the change and tested that it successfully enters the retry loop while the server is down (such as right this moment), but the logging needs to be adjusted and the initial attempt needs to be made with no delay, so I don't want to stuff it into my open PR.

**Comment by jpdillingham** [comment]
Proof of it working:

```
[slskd.Application] [17:59:40 INF] Starting system clock...
[slskd.Application] [17:59:40 INF] System clock started
[slskd.Application] [17:59:40 INF] Waiting about a second before reconnecting
[slskd.Application] [17:59:41 INF] Attempting to reconnect (#1)...
```

**Comment by colbsure** [comment]
I am experiencing identical behaviour in an LXD container, as of today.

"slskd" now refuses to connect with any user or port whilst the QT application ontinues to work with those same users/ports.

I am curious as to how this is solved with a connection watchdog.

**Comment by zliebersbach** [comment]
@jpdillingham when can we expect the a new release/Docker build including this fix to be available? slskd currently unusable due to this. Thanks for fixing so quickly! 🥇

**Comment by jpdillingham** [comment]
@zliebersbach I'm planning to create a release this evening

**Comment by jpdillingham** [comment]
@zliebersbach this is out in [0.21.0](https://github.com/slskd/slskd/releases/tag/0.21.0)
