### ISSUE TITLE
The "Rooms" page not displayed at the correct height

### ISSUE THREAD

**Issue by Rollbacke** [slskd/slskd#1151]
Hi,

I think a piece of code is missing somewhere, because when you arrive on the "Rooms" page, the top of the page (basically, the list of rooms to which you are subscribed) is hidden by the header.
It's systematic when we go back to it.

![hidden](https://github.com/slskd/slskd/assets/86650802/9993f3cb-ed0c-4229-9855-fe3ccb441eb3)

Thanks !

**Comment by jpdillingham** [comment]
This was fixed in #1148 but I neglected to reference this issue, thanks for reporting it!
