### ISSUE TITLE
How do I run this software on windows?

### ISSUE THREAD

**Issue by Aniconomics** [slskd/slskd#1179]
I downloaded and extracted the exe. I also disabled my antivirus to make sure the installation wasn't effected. Clicking on the exe opened up the command line with lines of text generating. But I don't know what's exactly wrong. It may have to do something with my username and password. I tried editing the configuration folder but I'm no good at this kind of stuff

![Capture](https://github.com/user-attachments/assets/3b3fc772-bba0-4a22-88f2-016cb9598187)

**Comment by Aniconomics** [comment]
I assume I has to input the username and password in this section of the configuration file?

I have tried different variations but none have worked

**Comment by Aniconomics** [comment]
> You need to set a username and password. The documentation for that is [here](https://github.com/slskd/slskd/blob/master/docs/config.md#username-and-password).

I assume I have to input the username and password in this section of the configuration file?

I have tried different variations but none have worked, putting my real user name and password, putting slskd for both the usernam and password. coppying these "--slsk-username" "--slsk-password" command lines. I also tried slotting my real username and password into the command lines.
![Capturehhh](https://github.com/user-attachments/assets/78013bbf-4f2f-488e-a56e-2ee8408fb692)

**Comment by jpdillingham** [comment]
In the application directory for slskd (which on Windows is `%localappdata%\slskd`), there is a `slskd.yml` file, which is copied from the `slskd.example` file you have loaded.  Inside of that file (not the example), you need to remove the `#` in front of the `soulseek`, `username`, and `password` lines to uncomment them, then enter your username and password after the colon.  That section of the file should look like:

```yaml
soulseek:
#   address: vps.slsknet.org
#   port: 2271
  username: <your username>
  password: <your password>
```

You can omit the `address` and `port` lines if you want.

**Comment by Aniconomics** [comment]
It worked, thank you
