### ISSUE TITLE
Ignore Feature

### ISSUE THREAD

**Issue by samhatter** [slskd/slskd#1182]
Hello, I wanted to notify y'all that the ignore blacklisted members feature that was just recently committed doesn't work as intended in room chats. I get the debug statements saying the message was ignored but it still shows up in the room chat. I think its due to how the RoomService.cs file is unchagned but I don't know much about C#. Thank you for working on this feature btw.

**Comment by jpdillingham** [comment]
@samhatter should be fixed now, give it a try and let me know! (I did test it this time though 😅)

**Comment by samhatter** [comment]
🎉🎉🎉🎉🎉
