### ISSUE TITLE
Feature request, button to clear old searches

### ISSUE THREAD

**Issue by yroyathon** [slskd/slskd#1230]
Perhaps under System >> Data, have an extra button to Clear All Searches.  Seems like it might fit right in there with clearing all downloads, clearing all uploads.

I delete new searches as I make them now, but over time I've accumulated hundreds or thousands of searches, and I don't see a painless way of getting rid of them (clicking the X 5 times a day, may take months...).  At some point accumulating too many searches may cause the web app to lag, so would be nice to have the ability to remove them.

I also have a search that's stuck and thinks it's still in progress, I am hoping to clear that one out as well.

**Comment by jpdillingham** [comment]
Thanks for the suggestion!  I agree that it's needed.

There's a [retention setting](https://github.com/slskd/slskd/blob/master/docs/config.md#data-retention) for other types of data, but I neglected to add it for searches.  This would help too.
