### ISSUE TITLE
[FeatureRequest] OpenAPI/Swagger documentation for the REST API

### ISSUE THREAD

**Issue by Schaka** [slskd/slskd#1237]
Would it be able to add this in? 
I'm not quite sure how easy this is in C#, as I've only ever developed plugins loaded as DLLs for separate software.

But I've started work on an application in Kotlin/Java that serves as a bridge between Lidarr and slskd - basically an Overseerr for music with recommendations built in.

Right now, I'm reverse-engineering the web UI and looking at your controller endpoints to figure out what to do.

**Comment by jpdillingham** [comment]
It's already integrated, you just need to turn it on: https://github.com/slskd/slskd/blob/master/docs/config.md#features

Note that several endpoints suffer from a bug that prevents them from working with usernames or room names with forward slashes (and probably other characters) in them.  I will fix them eventually, at which point strings will likely need to be base64 encoded when appearing in routes.  I may or may not maintain backwards compatibility, based on how many endpoints will be impacted.

**Comment by Schaka** [comment]
I'm sorry, I completely missed that when going through the docs. Sorry for taking up your time and thank you so much for developing slskd.

**Comment by jpdillingham** [comment]
Not a problem! Feel free to reach out any time.  I'm glad someone is working on Lidarr!
