### ISSUE TITLE
Add metadata to shared files

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#136]
The information collected about shared files is currently limited to the name and size only.  Select a third party library (or, if it is straightforward enough, write something from scratch) to inspect files to determine the bitrate, sample rate and length.

This needs to be as fast as possible, as adding this feature is likely to double or triple the amount of time it takes for the application to scan shares.

This should support at least as many formats as Soulseek NS/Qt support, including .mp3, .flac, .wav, and .m4a as top priorities.  Support for more esoteric formats can be added later, if it isn't straightforward to do so now.

**Comment by tandy-1000** [comment]
Would it make sense at this stage to integrate with beets to provide this functionality? The beets db would definitely have this info, and for most people whose music shares will have a corresponding beets db, it might make sense...
Although beets integration is also a more long term feature such as Lidarr etc..

**Comment by mathiascode** [comment]
I wouldn't recommend writing this from scratch, unless you're really curious and want to delve into audio formats and their numerous quirks. On one hand, these formats rarely evolve after you've implemented them once, but it can be rather easy to make mistakes if you're not careful enough (I recently realized this when contributing a bunch of fixes to https://github.com/devsnd/tinytag, a Python audio metadata library we use in Nicotine+).

**Comment by jpdillingham** [comment]
I'll use https://github.com/mono/taglib-sharp for this.

**Comment by jpdillingham** [comment]
I'll do some benchmarking/investigating to see if maybe https://github.com/Zeugma440/atldotnet is a better fit.

**Comment by mathiascode** [comment]
Ideally, you would be able to skip tag reading, and only get the duration/bitrate. ATL seems to provide a way to do this, at least: https://github.com/Zeugma440/atldotnet/blob/f26d926ee2926f89cc934f4fc179b8feff9df709/ATL/AudioData/MetaDataIO.cs#L53-L56

**Comment by jpdillingham** [comment]
ATL has internal mechanisms for skipping ID3 tags and lazily loading images but from what I can tell there's no public API that exposes it.

I played around with TagLib a bit this morning and discovered that it has the ability to lazily load pictures, and the objects it creates implement `IDisposable`:

```
using var tfile = TagLib.File.Create(file, TagLib.ReadStyle.Average | TagLib.ReadStyle.PictureLazy);
```

TagLib is now considerably faster (other than some outliers):

```
$ ./MetadataBenchmark.exe
Enumerated 1744 files.  Starting benchmark...
Run: 1
ATL completed in 2289ms
TagLib completed in 591ms
Run: 2
ATL completed in 817ms
TagLib completed in 441ms
Run: 3
ATL completed in 811ms
TagLib completed in 1495ms
Run: 4
ATL completed in 2347ms
TagLib completed in 432ms
Run: 5
ATL completed in 818ms
TagLib completed in 421ms
```

I edited the source of TagLib and commented out the logic that reads metadata from mp3 and flac files, and as far as I can tell it doesn't make a difference.  I'm guessing that there's some buffering going on.
