### ISSUE TITLE
How can users see if they're sharing files and what they are? #Question #Help

### ISSUE THREAD

**Issue by ldexterldesign** [slskd/slskd#142]
Hi JP,

Thanks, as always, for super useful software

How can users see if they're sharing files and what they are?

I'm trying to map my share path to another Docker container's path but if I recall correctly containers can't see each other unless they're part of the same service..?

In any case, ability to see a) if I'm sharing files and b) what they are would help me problem solve this

Hope to hear back

Cheers

**Comment by jpdillingham** [comment]
The only way now is to browse yourself via slskd or another app.

**Comment by ldexterldesign** [comment]
Thanks for reply

Mmm, I can browser other user files so chalk it up to this:
> [...] if I recall correctly containers can't see each other unless they're part of the same service..?

I'll play with Docker when I have time and post back if I can't fix

Cheers
