### ISSUE TITLE
Bug: Config file not being respected

### ISSUE THREAD

**Issue by tandy-1000** [slskd/slskd#154]
I initially opened a discussion, but realised that I was facing a bug.
On the 0.13 release the config file is being loaded, but the values in it are not being used.

Run `slskd -c config.yaml` with the following example config file, `config.yaml`:
```
slskd:
  debug: true
```
and the program will not launch in debug mode.

When forcing debug output with a command line arg, you can see that the config file is loaded but for some reason is not being used.

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I've recently switched from using environment variables to the yaml file during development so I doubt a ton of things are broken or I would have noticed, but I'll take a look at the debug setting.

**Comment by jpdillingham** [comment]
I just tried this on a freshly installed system and it worked:

```
 ~/Downloads/slskd/slskd-0.13.0-osx-x64  ./slskd -c config.yaml
Configuration:
slskd:
  configurationfile=config.yaml (CommandLineConfigurationProvider)
  debug=true (YamlConfigurationProvider for 'config.yaml' (Optional))
```

Are you sure your config file is in place?  If not you should get a warning like:

```
[13:03:54 WRN] Specified configuration file 'nope.yml' could not be found and was not loaded.
```

**Comment by tandy-1000** [comment]
This is what happens when I try to start slskd:
![image](https://user-images.githubusercontent.com/24867509/130054961-5f3fb103-83c1-49fd-95c8-99d2234a0c2f.png)


Here is my config file:
```
 slskd:
   debug: true
   web:
     port: 9798
     url_base: /slskd
     authentication:
       disable: false
       username: ...
       password: ...
   directories:
     app: /opt/slskd
     incomplete: /mnt/extdrive/slsk/incomplete
     downloads: /mnt/extdrive/slsk/completed
     shared: ["/mnt/bigdrive/music"]
   soulseek:
     username: ...
     password: ...
     listen_port: 57264
```

Here is a tree of my slskd folder:
```
/opt/slskd/
├── config
│   └── slskd.yml
├── etc
│   └── slskd.xml
├── LICENSE
├── logs
│   ├── slskd-20210818.log
│   └── slskd-20210819.log
├── slskd
└── wwwroot
    ├── asset-manifest.json
    ├── favicon.ico
    ├── index.html
    └── static
    ....
```

Here is my systemd service file:
```
[Unit]
Description=slskd
After=network-online.target
Wants=network-online.target
ConditionPathExists=/mnt/bigdrive/music

[Service]
User=slskd
WorkingDirectory=/opt/slskd
ExecStart=/opt/slskd/slskd -c /opt/slskd/config/slskd.yml
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by jpdillingham** [comment]
Sorry, there was a subtle change to how the yaml works that I neglected to document.  The top-level `slskd` element is no longer valid; everything under it needs to be in the root of the file.

I've updated the release notes to document this, and I'll commit to being more careful about configuration changes in the future.  I didn't think anyone but me was really using this :)

**Comment by tandy-1000** [comment]
No worries! Thank you for your time. It's a great piece of software and its nice to see it being maintained so well.

**Comment by tandy-1000** [comment]
I've just tested the new release, everything + aliases are working smoothly, thanks.
