### ISSUE TITLE
Improvements to search responses

### ISSUE THREAD

**Issue by mathiascode** [slskd/slskd#158]
A few improvements could be made to search responses:

- Currently, no results seem to be returned unless the the search string is a substring of the file path. E.g. if the path of a shared file is `Shares/Music/This is a Song.mp3`, searching for `music mp3 song` or `this mp3` yields no results, while `this is a song mp3` does.

- Handle partial search terms (*ello) and excluded search terms (-hello) when responding to search requests. SoulseekQt implements a client-side filter for excluded search terms when displaying search results in the UI, in case the sender doesn't honor exclusions, but SoulseekNS does not. These special search terms are probably less urgent nowadays, since they are only mentioned/documented in Soulseek NS's UI, but I've implemented them in Nicotine+ earlier today for increased compatibility: https://github.com/nicotine-plus/nicotine-plus/commit/859327e42ce4dc531339a5b7e83cbb9c8714de31

**Comment by jpdillingham** [comment]
Thanks for the heads up on the first point.  I'm using the [FTS5](https://www.sqlite.org/fts5.html) extension to SQLite for full text searching; I implemented it and didn't care to test stuff like this, assuming it would be handled.  I'm hopeful that there's some nuance to the syntax I missed, as I couldn't really come up with a fast way to scan shares for matching terms.

Regarding exclusions, I somehow got the impression that excluded terms, along with other search filters, were strictly client side only and not passed through to the server.  I probably would have been testing with Qt exclusively though, so it makes sense that it may have been missed.

**Comment by mathiascode** [comment]
> Regarding exclusions, I somehow got the impression that excluded terms, along with other search filters, were strictly client side only and not passed through to the server. I probably would have been testing with Qt exclusively though, so it makes sense that it may have been missed.

Exclusions feel like a leftover from the Soulseek NS days. Although they still work the same in SoulseekQt, they're not mentioned anywhere. As far as I'm aware, the client-side filter box was a SoulseekQt addition.

Soulseek NS seems to have no client-side filtering at all, gladly accepting any search results it receives. I believe this was changed in SoulseekQt to filter out irrelevant results sent by some bugged client at one point.

**Comment by jpdillingham** [comment]
I get what you were saying about NS now.  Playing around with the matching improvements this morning, I can send queries to slskd that it matches (like foo*) and returns results for, but Qt refuses to display them.  Kind of a bummer, but I also get it, as bad actors could return junk for every query.

#159 fixes the strict ordering issue, I'll iterate a bit more and implement exclusions before merging.

**Comment by mathiascode** [comment]
> I can send queries to slskd that it matches (like foo matching foos) and returns results for, but Qt refuses to display them.

I feel that partial matching would quickly result in a slew of irrelevant results (e.g. the -> these, their, theme, theatre), especially with short words, so I prefer Qt's behavior.

**Comment by jpdillingham** [comment]
I've captured the wildcard matching work in #160, but that's blocked for the time being so I'm considering this work complete for the time being.

@mathiascode  As always, I really appreciate your input!
