### ISSUE TITLE
Unable to login in 0.13.4

### ISSUE THREAD

**Issue by pavlukivan** [slskd/slskd#195]
When using 0.13.3, everything works fine. However in 0.13.4, when I set slskd up (using either docker or the release build) it simply continuously refreshes the page and isn't showing anything.

**Comment by jpdillingham** [comment]
Confirmed the issue (I don't make a habit out of testing with security enabled, but clearly I should).

I'll have a fix in a few hours when I'm done with my day job.

**Comment by jpdillingham** [comment]
This is fixed in 0.13.5.  You may need to clear your cache.

**Comment by jpdillingham** [comment]
I've created issue #197 to further improve upon this.
