### ISSUE TITLE
Add the ability to cancel search requests that are in progress

### ISSUE THREAD

**Issue by tandy-1000** [slskd/slskd#198]
It is easy to press enter and search for a typo, e.g. "beach boys pet souds". This would allow the user to cancel the search and not have to wait for it to complete. It doesn't seem there is any way to do this at the moment.

**Comment by jpdillingham** [comment]
Thanks for bringing this up.  There's code to do this [here](https://github.com/slskd/slskd/blob/master/src/slskd/Application/Search/SearchService.cs#L174-L188) but it needs an API endpoint, and then a button on the UI to cancel.
