### ISSUE TITLE
Add the ability to delete downloaded files

### ISSUE THREAD

**Issue by edgar-vincent** [slskd/slskd#205]
Hello,

I believe it might be useful to add a `Remove and delete` option in the Downloads tab, which would delete the selected files from the disc.

Thank you very much for your long-awaited and amazing work,

EV

**Comment by jpdillingham** [comment]
Moving this to the QOL milestone.

I like the idea of a "remove and delete" delete button on the download UI.

I think I will also add a "system" tab that will display the contents of the download folder and allow users to delete files from there as well.

**Comment by jpdillingham** [comment]
Released in [0.18.0](https://github.com/slskd/slskd/releases/tag/0.18.0)

**Comment by edgar-vincent** [comment]
Thank you very much for implementing this @jpdillingham!

> Moving this to the QOL milestone.
> 
> I like the idea of a "remove and delete" delete button on the download UI.
> 
> I think I will also add a "system" tab that will display the contents of the download folder and allow users to delete files from there as well.

If I am not mistaken, files can now be deleted for the "System" page, but not from the "Downloads" page. Am I right?

Thanks again!

**Comment by jpdillingham** [comment]
@edgar-vincent yep just from 'System'.  I can add another issue to allow deletion from the Uploads/Downloads page, not sure why I didn't think of that
