### ISSUE TITLE
Download whole folder when selecting a file in the search

### ISSUE THREAD

**Issue by steinuil** [slskd/slskd#241]
In SoulseekQT when you want to download a file from the search tab, it shows you the whole folder and lets you select other files that are contained in it.

It'd be nice to have this option in the slskd UI too, right now I have to find the user and get the whole file list and find it there.

Thanks again for the project, I managed to set it up on my rpi and it's working really well so far!

**Comment by jpdillingham** [comment]
Thanks for raising this.  

The functionality in Soulseek.NET exists through the `GetDirectoryContentsAsync()` method, so implementation would be fairly straightforward, consisting of:

* [ ] Add a new API endpoint to `UsersController` (e.g. GET `{username}/directory/{directoryName}`), map and return the response from `GetDirectoryContentsAsync()`
* [ ] Add a modal to the UI that requests the contents of a directory and displays the result (leverage existing search/browse components).
* [ ] On the search UI, add an additional button to the list of actions for search responses that opens the modal

I've added the `help wanted` tag as this is a lower priority for me at the moment, but I'd be happy to help someone else tackle it.

**Comment by mattgoldspink** [comment]
I feel like this ticket is done? We already have the get folder contents on the search results now which grabs them all and then it's easy to pick all the files. Am I missing something?

**Comment by jpdillingham** [comment]
Good catch! The linked PR just didn't use one of the magic closing words.
