### ISSUE TITLE
Bug: empty search results in repeated searches happening

### ISSUE THREAD

**Issue by tandy-1000** [slskd/slskd#246]
If you search "" then slskd gets stuck in a search loop.
Would be solved by https://github.com/slskd/slskd/issues/198.
I was able to fix this by deleting `search.db`.

**Comment by jpdillingham** [comment]
This ties in with #84 also.  This might be related to a bug I've seen randomly where a search completes with results but nothing is displayed.

Either way the whole search interface needs an overhaul.

**Comment by tandy-1000** [comment]
> This ties in with #84 also. This might be related to a bug I've seen randomly where a search completes with results but nothing is displayed.

Yeah this is probably that bug

**Comment by jpdillingham** [comment]
This is a timing issue, where searches complete and persist results to the database, but calling the database to retrieve results returns nothing.  I've added a 500ms wait to the UI, hopefully that's more than enough time.  This may require a retry loop.
