### ISSUE TITLE
Add ability to have multiple concurrent searches

### ISSUE THREAD

**Issue by tandy-1000** [slskd/slskd#249]
It would be nice to be able to open a new tab and load slskd and make another search e.g. when waiting for long searches.

**Comment by jpdillingham** [comment]
My goal is to eventually treat searches like transfers, so when you initiate a search it'll go into a list of searches, where multiple can be running concurrently, and then you can switch among them to see results, delete old searches, etc.

This is one of the big boulders that needs to be cleared before Lidarr (or other) integration can move forward.

**Comment by ldexterldesign** [comment]
Awesome feature ❤️❤️❤️!

Thanks both
