### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by Pheggas** [slskd/slskd#268]
Hello. In your documentation, there's written that default login is slskd and password also slskd but that's not true. At least with docker-compose default config.

Here:
![image](https://user-images.githubusercontent.com/9994511/141796803-495c2208-36bb-44b6-a8ac-964403304acf.png)

You have login:
Username: <slskd username>
Password: <slskd password>

And actually these credentials are the right one. Please fix those.

**Comment by jpdillingham** [comment]
I'll be rewriting all of the documentation to reflect recent changes shortly, probably over the weekend.
