### ISSUE TITLE
Error resolving search response

### ISSUE THREAD

**Issue by Pheggas** [slskd/slskd#269]
Hello. I looked into logs and noticed a lot of these:
![image](https://user-images.githubusercontent.com/9994511/141815205-b993d24d-da97-4e89-b9b5-70801c4bf63d.png)

**What does it mean exactly?**

**Comment by jpdillingham** [comment]
This is captured in #252, it's an internal bug that I haven't gotten to yet.

**Comment by jpdillingham** [comment]
@Moondownr @Pheggas I've been unable to reproduce this on my end, so I don't think filenames are causing the issue.  I've enabled verbose logging of share configuration in #301 and that change will be out in the canary build in a few minutes.  Can I get you to confirm whether you're still experiencing this issue, and if so, share the logs that look like:

```
 Share: Alias: foo Mask: @@mzaod Local Path: \\some\path Remote Path: @@mzaod\foo Raw: ...
```

**Comment by jpdillingham** [comment]
I believe I've tracked the issue down to files containing two single quotes (e.g. `fo''bar`).  These get replaced with a single quote.

**Comment by Moondownr** [comment]
Sorry, didn't have time to upgrade to canary yet. I checked my recent logs and here is a nice big chunk of these errors, though.
[errors.txt](https://github.com/slskd/slskd/files/7711691/errors.txt)

None of the path contain ''. and although I first thought that all of them have two single quotes total (spaced out), that's also not the case, i.e:

`@@quzqt/Music/03-Neopsychedelic, Stoner, Vintage/Darker My Love/Darker My Love - Moccasin split 12' (I Hate Rock N Roll Records)/03. Moccasin - The Rule of Queen Tsago.mp3
`

No second single quote to be found

**Comment by Moondownr** [comment]
You are absolutely right re:double single quotes.

Here are recent errors from my log
[errors.txt](https://github.com/slskd/slskd/files/7711752/errors.txt)
s (haven't upgraded to canary) for reference. Double single quotes in file names get replaced by a single quote in logs.

[errors.txt](https://github.com/slskd/slskd/files/7711749/errors.txt)

**Comment by jpdillingham** [comment]
Thanks for confirming!  I was able to reproduce the problem locally and just pushed a change in #303 that should solve it.  The canary should be out in about 30 minutes.
