### ISSUE TITLE
Queries with spaces in them don't get results

### ISSUE THREAD

**Issue by kromsam** [slskd/slskd#316]
For instance, when I use the query `Michael Jackson`, has no results, but `Jackson` has thousands. I use the latest version of the container!

**Comment by jpdillingham** [comment]
There are a number of terms that the server won't send on to the network, that being one of them.  Here's a relevant Reddit post: https://www.reddit.com/r/Soulseek/comments/m32go4/n00b_protip_some_artists_names_are_banned_get/

**Comment by kromsam** [comment]
haha, well im sorry to bother then. i thought id use that term to check if my connection works

**Comment by jpdillingham** [comment]
No problem, it will be a common question and it's good to have it documented!
