### ISSUE TITLE
Investigate issue with shares configured via symlink

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#320]
Reported in #155 

It seems symbolic links with .NET Core might be a bit of a contentious issue, and probably doesn't work as transparently as I would have assumed.  I'll need to try configuring a share and see what happens.  There may be a way to differentiate directories from symlinks and resolve them differently.

**Comment by ppom0** [comment]
I think I have this issue. It seems like it shares the file, but only the first bytes, same length of the symlink itself. Not sure though, it's hard to debug.

**Comment by jpdillingham** [comment]
@ppom0 FYI this is fixed in #1165
