### ISSUE TITLE
Dockerfile healthcheck hardcoded Port

### ISSUE THREAD

**Issue by dvd741-a** [slskd/slskd#324]
Please change the dockerfile health check to use the environmental variable. Currently it's hardcoded to do a wget on :5000/health

Environmental variable: $SLSKD_HTTP_PORT

More info: https://stackoverflow.com/questions/67286967/dockerfile-healthcheck-with-environment-variable

**Comment by jpdillingham** [comment]
Thanks, hadn't considered this.
