### ISSUE TITLE
Infinite loading with single-character search term

### ISSUE THREAD

**Issue by mathiascode** [slskd/slskd#326]
If you attempt a search with a single-character search term, e.g. `a` or `x`, the search page keeps loading until you press `Esc`.

![Screenshot from 2022-01-13 02-32-16](https://user-images.githubusercontent.com/8754153/149244682-ac600bf5-8541-4d63-8893-62ff1dd8bfa3.png)

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I think the fix is going to involve disallowing single character searches.  I need to review the logic but I think I toss those out (and I think other clients ignore them, or the sever strips them, I can't remember which)

**Comment by mathiascode** [comment]
> Thanks for reporting this. I think the fix is going to involve disallowing single character searches. I need to review the logic but I think I toss those out (and I think other clients ignore them, or the sever strips them, I can't remember which)

Modern clients only respond to >=3 character search requests, but the server still allows single-character search terms. Of course it's useless for almost everyone, but I use single-character search requests as a hack to quickly find SoulseekNS users and other older clients.

**Comment by jpdillingham** [comment]
Fixed in #467 and #469

![image](https://user-images.githubusercontent.com/17145758/169288811-860502a3-df2c-41ba-85c4-e8f0538e92ce.png)
