### ISSUE TITLE
Soulseek connection might "thrash" and cause a connect/disconnect cycle

### ISSUE THREAD

**Issue by Moondownr** [slskd/slskd#331]
Today this started happening all of a sudden

![image](https://user-images.githubusercontent.com/23419209/151637428-988d2a61-96d6-470c-a99e-17d39ff6c3be.png)

![Screenshot 2022-01-29 at 01-31-56 Pi-hole - minimoon](https://user-images.githubusercontent.com/23419209/151637437-603ac117-b0c9-455c-a186-76d7220e5b87.png)

I killed slskd and it stopped. First time seeing this behavior (I check my pi-hole semi-regularly). Looks a bit... excessive.

**Comment by Moondownr** [comment]
I'm suspecting it might have been a weird firewall issue, possibly unrelated to slskd itself. Currently everything is working fine again.

**Comment by jpdillingham** [comment]
The only way I can see this happening is if the reconnect code malfunctioned and was trying to connect to the server like crazy with very little delay.  If that were really the case I think you would have been banned from the server.

It does look like there's a potential edge case where the client might connect successfully and then immediately disconnect, in which case the exponential backoff calculation will reset.  I'll add some logic to detect this and prevent thrashing if it does happen.

**Comment by jpdillingham** [comment]
Not sure how this was closed, it's still a problem.

At first glance it appears the issue is that multiple threads are created, each with its own retry loop.  At least, that's what it looks like.

```
19:39:23 | INF | Waiting about 301 seconds before reconnecting
19:39:23 | ERR | Failed to reconnect: "The client is already connected
19:39:23 | INF | Attempting to reconnect (#163)...
19:39:22 | INF | Waiting about 301 seconds before reconnecting
19:39:22 | ERR | Failed to reconnect: "The client is already connected
19:39:22 | INF | Attempting to reconnect (#165)...
19:39:12 | INF | Waiting about 301 seconds before reconnecting
19:39:12 | ERR | Failed to reconnect: "The client is already connected
19:39:12 | INF | Attempting to reconnect (#163)...
19:39:09 | INF | Waiting about 301 seconds before reconnecting
19:39:09 | ERR | Failed to reconnect: "The client is already connected
19:39:09 | INF | Attempting to reconnect (#164)...
19:39:08 | INF | Waiting about 301 seconds before reconnecting
19:39:08 | ERR | Failed to reconnect: "The client is already connected
19:39:08 | INF | Attempting to reconnect (#161)...
19:39:07 | INF | Waiting about 301 seconds before reconnecting
19:39:07 | ERR | Failed to reconnect: "The client is already connected
19:39:07 | INF | Attempting to reconnect (#167)...
19:39:07 | INF | Waiting about 301 seconds before reconnecting
19:39:07 | ERR | Failed to reconnect: "The client is already connected
19:39:07 | INF | Attempting to reconnect (#163)...
19:39:05 | INF | Waiting about 301 seconds before reconnecting
19:39:05 | ERR | Failed to reconnect: "The client is already connected
19:39:05 | INF | Attempting to reconnect (#168)...
19:39:04 | INF | Waiting about 301 seconds before reconnecting
19:39:04 | ERR | Failed to reconnect: "The client is already connected
19:39:04 | INF | Attempting to reconnect (#163)...
```
