### ISSUE TITLE
Docker paths

### ISSUE THREAD

**Issue by Eric-sson** [slskd/slskd#347]
I am trying to run this on Unraid with docker.
What would be the correct way to mount the paths downloads, incomplete and shared?
I have tried so far /app/downloads/, /var/slskd/downloads/ and /downloads/ but all still download in the app directory.

**Comment by jpdillingham** [comment]
You'll need to override the locations of the downloads and complete directories using one of the options described here: https://github.com/slskd/slskd/blob/master/docs/config.md#incomplete-and-downloads

For example, if you're mounting volumes `/downloads` and `/incomplete`, you'd set the environment variables:

```
SLSKD_DOWNLOADS_DIR=/downloads
SLSKD_INCOMPLETE_DIR=/incomplete
```

That's the intent anyway.  Let me know if it doesn't work!

**Comment by debbinkm** [comment]
I am not 100% sure what you're asking, but my configuration is this:
In slskd.yml I have:
```
directories:
  incomplete: /app/incomplete
  downloads: /downloads
  shared:
    - /shared
```
In docker-compose.yml I map the directories that I want access to (shared and downloads):
```
volumes:
  - /volume2/docker/vpnStack/slskd/config:/app
  - /volume1/data/newMusic:/downloads
  - /volume1/data/media/music:/shared:ro
```
"ro" on my shared volume is probably not necessary, but I wanted to be extra-sure that my music doesn't get changed/corrupted somehow.

Also, I am not running on Unraid, but I don't think that should substantially change anything.

**Comment by Eric-sson** [comment]
Thanks for your help. I have it working now :) 
For future references here is the docker compose:

version: "3"
services:
  slskd:
    container_name: slskd
    entrypoint:
      - ./slskd
    environment:
      - PGID=100
      - PUID=99
      - SLSKD_SLSK_USERNAME=*****
      - SLSKD_SLSK_PASSWORD=*****
      - SLSKD_SHARED_DIR=/music
      - HOST_OS=Unraid
      - TCP_PORT_50000=50000
      - TCP_PORT_5000=5000
      - SLSKD_DOWNLOADS_DIR=/complete
      - SLSKD_INCOMPLETE_DIR=/incomplete
      - TZ=Europe/Paris
      - TCP_PORT_5001=5001
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_BUNDLE_EXTRACT_BASE_DIR=/var/tmp/.net
      - SLSKD_HTTP_PORT=5000
      - SLSKD_HTTPS_PORT=5001
      - SLSKD_SLSK_LISTEN_PORT=50000
      - SLSKD_APP_DIR=/app
      - SLSKD_DOCKER_TAG=0.0.1
      - SLSKD_DOCKER_VERSION=0.14.3.0-a32cc97
      - SLSKD_DOCKER_REVISON=0
      - SLSKD_DOCKER_BUILD_DATE=
    expose:
      - 5000/tcp
      - 50000/tcp
      - 5001/tcp
    hostname: Tower
    image: slskd/slskd
    ipc: private
    labels:
      org.opencontainers.image.authors: slskd Team
      org.opencontainers.image.created: ""
      org.opencontainers.image.description: A modern client-server application for
        the Soulseek file sharing network
      org.opencontainers.image.documentation: https://github.com/slskd/slskd
      org.opencontainers.image.licenses: AGPL-3.0
      org.opencontainers.image.revision: 0
      org.opencontainers.image.source: https://github.com/slskd/slskd
      org.opencontainers.image.title: slskd
      org.opencontainers.image.url: https://slskd.org
      org.opencontainers.image.vendor: slskd Team
      org.opencontainers.image.version: 0.14.3.0-a32cc97
    logging:
      driver: json-file
      options:
        max-file: 1
        max-size: 50m
    networks:
      - host
    volumes:
      - /mnt/remotes/SYNOLOGY_data/usenet/music/complete/:/complete:rw
      - /mnt/remotes/SYNOLOGY_data/usenet/music/incomplete/:/incomplete:rw
      - /mnt/remotes/SYNOLOGY_data/media/music/:/music:rw
      - /mnt/user/appdata/slskd:/app:rw
    working_dir: /slskd
networks:
  host:
    external: true
