### ISSUE TITLE
Add leech detection

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#361]
Come up with a way to classify "leechers" and, and identify them within the application by adding them to the "leechers" built-in group.

Using number of shared files is a good start (and perhaps the only metric), with a user-configurable threshold.  

The logic to determine whether a user is a "leecher" and more specifically, whether that user's effective group should be the internal `leechers` group, the following rules should be applied:

* If the user's shared file and folder count is below the configured threshold, the user is a "leecher"
* If a user is a leecher but has been explicitly added to a user-defined group, the effective group for that user is the defined group.
* If a user is a leecher but has privileges on the network, the effective group for that user is the privileged group.
* If a user is a leecher, has not been explicitly added to a user-defined group, and does not have privileges on the network, the effective group for that user is the leecher group.

**Comment by jpdillingham** [comment]
#364 laid a lot of groundwork for this by ensuring that user statistics (including number of shared files and folders) are synchronized starting from the moment a user enqueues a file.  This information should be used within the `GetGroup` implementation in `UserService` to determine whether the user is a leecher.

**Comment by mathiascode** [comment]
Note that file/folder stats sent from SoulseekQt clients to the server can be unreliable at times: https://github.com/nicotine-plus/nicotine-plus/issues/1565

**Comment by jpdillingham** [comment]
Thanks for the heads up.  Leech detection has never been a favorite feature of mine and the fact that we can't even accurately detect counts without browsing the user makes it so much worse.

I'm going to proceed with the counts from the server, and I'll consider adding an asynchronous/lazy fetch of user shares after an upload has enqueued to double-check the numbers later.

I think I'll probably bump the minimum speed limit up to 100KiB/s, from 1KiB/s, to soften the blow if users mistakenly get tagged as leechers.  I hadn't planned on sending a message and definitely won't now.  Users can either find the files somewhere else or wait for them.  It's not ideal, but it isn't as bad as outright refusing to share with them.
