### ISSUE TITLE
Assign users with network privileges to the built-in 'privileged' group

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#362]
The server sends a list of privileged users when the client first connects, and additional events when users become privileged.  Privileges expire, however, and the server doesn't inform us when that happens.

The best approach would be to create a cache and fill it with the list of usernames we receive on connect or through events.  Usernames should remain in the cache for 24 hours (privileges are tracked by number of days).

When a user attempts to enqueue an upload, we should use `GetUserPrivilegedAsync(username)` to see if they are privileged, and if so, add their username to the cache for 24 hours.

**Comment by mathiascode** [comment]
You could use the `privileged` attribute in the `GetUserStatus/7` and `ConnectToPeer/18` server messages to update this status more frequently (I assume it was later added to these messages for this reason). IIRC, the official clients don't use the `UserPrivileged/122` server message anymore, but since it still works, it's probably fine to use if you want to.

**Comment by jpdillingham** [comment]
Thanks, I had forgotten those messages had flags in them.  Disappointingly, I've discovered that the server no longer sends `AddPrivilegedUser/91` or `NotifyPrivileges/124`, sending private messages directly to the effected user instead.

I'm guessing that the trick here is to send `GetUserStatus/7` before making any decisions about how to process the queue, which makes sense and solves my dilemma about how long to cache privileges.

**Comment by mathiascode** [comment]
> I'm guessing that the trick here is to send `GetUserStatus/7` before making any decisions about how to process the queue, which makes sense and solves my dilemma about how long to cache privileges.

In Nicotine+, i send `GetUserStatus/7` in addition to `AddUser/5`, which I believe SoulseekQt does too. I don't remember if SoulseekQt sends any `GetUserStatus/7` messages manually after this, but I suppose users switching between online and away status + ConnectToPeer messages when requesting new files (from modern clients that attempt direct and indirect connections concurrently) would update the privilege status often enough.

**Comment by jpdillingham** [comment]
What I ended up doing is explicitly sending `GetUserStatistics` each time a `GetUserStatus` response is received, and sending both immediately after `AddUser`.  This ensures that statistics are updated each time user status changes, but it does cause an extra round-trip to the server when the user is initially added.

I haven't seen user statistics sent unsolicited, which I would have expected when the user updates their shares.  Although, I suppose average speed is in there too, which is updated each time an upload completes, so maybe it worked this way at one point but the extra traffic wasn't worth it.

**Comment by mathiascode** [comment]
> I haven't seen user statistics sent unsolicited

This shouldn't be the case. If you watch a user by sending a `AddUser` message to the server, the server should always send `GetUserStatus` and `GetUserStatistics` messages whenever the user status or a stat changes.

> which I would have expected when the user updates their shares.

Were you observing a SoulseekQt client? For some reason, SoulseekQt only sends the number of files and folders to the server on startup, but not when rescanning shares later.

**Comment by jpdillingham** [comment]
Yep, I only tested with Qt.  This is good to know, and I'm glad I left the code to handle unsolicited messages in.
