### ISSUE TITLE
Changes to .yml config not actually loaded

### ISSUE THREAD

**Issue by Hexactly** [slskd/slskd#408]
Trying to log in after completing docker compose setup on synology nas running dsm 7.
everything starts up but I get an error:

> Not connecting to the Soulseek server; username and/or password invalid.  Specify valid credentials and manually connect, or update config and restart.

Tried two different confirmed working soulseek accounts.

Not sure what I'm missing, any help would be appreciated to the get this working for me :)
Here's the complete startup log:

>today at 14:46:56[11:46:56 INF] Version: 0.15.1.0 (0.15.1.0-63a34dc)
today at 14:46:56[11:46:56 INF] Invocation ID: 6c6bfb15-6e12-4c42-9149-5b82d1832354
today at 14:46:56[11:46:56 INF] Process ID: 1
today at 14:46:56[11:46:56 INF] Instance Name: default
today at 14:46:56[11:46:56 INF] Using application directory /app
today at 14:46:56[11:46:56 INF] Using configuration file /app/slskd.yml
today at 14:46:56[11:46:56 INF] Listening for HTTP requests at http://0.0.0.0:5000/
today at 14:46:56[11:46:56 INF] Listening for HTTPS requests at https://0.0.0.0:5001/
today at 14:46:56[11:46:56 INF] Using randomly generated self-signed certificate
today at 14:46:58[11:46:58 INF] Using base url /
today at 14:46:58[11:46:58 INF] Serving static content from /slskd/wwwroot
today at 14:46:58[11:46:58 WRN] Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
today at 14:46:58[11:46:58 INF] Configuring client
today at 14:46:58[11:46:58 INF] Client configured
today at 14:46:58[11:46:58 INF] Listening on port 50000
today at 14:46:58[11:46:58 INF] Checking GitHub Releases for latest version
today at 14:46:59[11:46:59 INF] Scanning shares
today at 14:46:59[11:46:59 WRN] Not connecting to the Soulseek server; username and/or password invalid.  Specify valid credentials and manually connect, or update config and restart.
today at 14:46:59[11:46:59 WRN] Aborting shared file scan; no shares configured.
today at 14:46:59[11:46:59 INF] Scanned 100% of shared directories.  Found 0 files so far.
today at 14:46:59[11:46:59 INF] Shares scanned successfully. Found 0 directories and 0 files in 161.4957ms
today at 14:46:59[11:46:59 INF] Version 0.15.1.0 is up to date.<

**Comment by Hexactly** [comment]
Now understand that the yml file I'm editing isn't the one that is being loaded.
Tried to simply change the web ui login but doesn't work.
I'm editing slskd.yml under '/docker/appdata/slskd' the n running the container
When I view slskd.yml from '/slskd/config' from the container console it shows the original setup without my changes.

Using the following compose:

`  slskd:
    container_name: slskd
    image: slskd/slskd:latest
    restart: always
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    labels:
      - org.hotio.pullio.update=${PULLIO_UPDATE}
      - org.hotio.pullio.notify=${PULLIO_NOTIFY}
      - org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}
    ports:
      - 5000:5000
      - 5001:5001
      - 50000:50000
    volumes:
      - ${DOCKERCONFDIR}/slskd:/app
      - ${DOCKERSTORAGEDIR}/media/music:/music
`

**Comment by Hexactly** [comment]
I've tried this on windows as well.
Edited the slsk.yml file under the profile folder (and any other location I could find)

Still no change, running the app always loads the original config file with default values.

I can't get my head around this... must be something I'm doing wrong.

Any help would be great!

Thanks

**Comment by Hexactly** [comment]
I managed to run using the --debug flag

the config file shown is the default one, doesn't contain the change I made.

The path to the .yml file shown is identical to the one i'm editing.

**Comment by Hexactly** [comment]
Made some progress using the flag for user name and password and remote editing.
I now see my user details and can edit the config via web.
When I make a change to the config via web and save I get this error:
>Value cannot be null. (Parameter 'instance')

And still can't figure out why changes to the .yml aren't being loaded.

**Comment by jpdillingham** [comment]
If you're able to edit the yml from the UI, the file is being updated and reloaded (saving just writes to the file).  If you're editing it manually and the changes aren't reflected, you may have an error in your yaml formatting

**Comment by Hexactly** [comment]
I'm able to pass the debug flag using cmd but can't use any other flags.
Tried using --config to point to the .yml (same and different locations).
I made one change to the .yml - web user name but can't get it to load in any way I try.

> slskd.exe --debug --config-C:\tmp\slskd.yml

> configurationfile=C:\Users\Yonatan\AppData\Local\slskd\slskd.yml (DefaultValueConfigurationProvider)
> debug=true (CommandLineConfigurationProvider)

>[13:28:09 INF] Using configuration file C:\Users\Yonatan\AppData\Local\slskd\slskd.yml

**Comment by Hexactly** [comment]
The config file in "C:\Users\Yonatan\AppData\Local\slskd\slskd.yml"
Contains this line:
> #     username: slskd1

but the debug info when running shows:
> username=slskd (DefaultValueConfigurationProvider)

**Comment by jpdillingham** [comment]
Just to rule out a problem with the contents of the config file, delete it or rename it to `slskd.yml.bak` or something.

Start the app, and you should see:

```
[06:29:23 WRN] Configuration file C:\Users\<user>\AppData\Local\slskd\slskd.yml does not exist; creating from example
```

You should end up with a slskd.yml that is completely commented out.  The first few lines should be:

```yml
# debug: false
# no_logo: false
# no_start: false
```

Edit it so that the first few lines are (only edit the first line):

```yml
debug: true
# no_logo: false
# no_start: false
```

Restart the app, and you should see the debug view, and:

```
  debug=true (YamlConfigurationProvider for 'slskd.yml' (Optional))
```

If this works then the application is loading the yaml correctly.  From there you should have no problem updating the file and seeing the changes reflected when you run the app.

**Comment by Hexactly** [comment]
Wow sometimes the answer is right there... seems I didn't remove the comment char for all lines in the config.

All good now! thanks for your time and patience :)
