### ISSUE TITLE
Failure to scan a share containing files with no extension

### ISSUE THREAD

**Issue by recordscience** [slskd/slskd#410]
`20:08:34 WRN] Failed to scan files in directory /mnt/what/ever: startIndex cannot be larger than length of string. (Parameter 'startIndex')`

ive got around 10k files in one directory, can this be fixed?

**Comment by jpdillingham** [comment]
This is going to be a formatting bug with one or more of the filenames; `startIndex` is related to code that masks files.

Can you provide your share config (path and any alias)?  It would also be helpful if you could run `ls -Rla > files.txt` from the root of your share and email the result to logs@slskd.org

**Comment by jpdillingham** [comment]
Thanks for the logs.  The problem is with files that have no extension (in your case, `!ogg`).  I'll have a fix shortly.
