### ISSUE TITLE
search loop when disconnected from slsk network

### ISSUE THREAD

**Issue by davidzx** [slskd/slskd#437]
this kinda ties in with the empty search bug [#246](https://github.com/slskd/slskd/issues/246). when disconnected from the slsk network with the ui button and then doing a search, slskd gets stuck searching without results, even when pressing the connect button. restarting the server does nothing, restarting the container does nothing, only deleting the search.db fixes it.

Version "0.15.2.0"
docker slskd/slskd:latest

**Comment by jpdillingham** [comment]
Thanks for reporting this.  It doesn't take much to break this, unfortunately, and and endless spinner is usually the result

**Comment by jpdillingham** [comment]
This was fixed with #467 and #469.  Searching with either no text, or while disconnected from the server will result in an error displayed via a 'toast' at the bottom of the screen.
