### ISSUE TITLE
Add a way to monitor share scans in real time

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#443]
It is incredibly hard to get any insight into the share scanning process as is, and I'm not sure that it is entirely bug-free as desired.

Users should be able to see file-by-file (or at least, directory-by-directory if per file isn't feasible) status of the scan, along with any errors encountered at the individual file level.

In addition, the process should surface the share information that is currently logged; share name and location, mask, aliasing, exclusions, etc.

At a high level this will require a new SignalR controller, some additional code in the share scanning library to emit diagnostic data, and some sort of user interface to watch the progress.

This would likely be best tackled as a grouped effort along with #422, #292, and #148 (which appears to have some duplication with 292)

**Comment by mathiascode** [comment]
There's an increasing number of users with files in the 100k - 2m range (up to 60k folders) in the `nicotine` room at least, something to keep in mind if you implement file-by-file or directory-by-directory status and make it accessible to regular users. Any kind of logging could quickly blow up here.

**Comment by jpdillingham** [comment]
For now the initial scan on start will bypass this and behave as it does today (for better or worse).  I'm imagining the detailed scan to be user initiated and asynchronous, so hopefully it wouldn't cause any issues.  But 💯 I do not want this data in my logs.

Thinking more through this, I think this effort really needs to be blocked by #138.  I've been hesitant to do this because the share is basically in a presumed-dirty state while a new scan is being performed, but the worst that will happen is that someone will get a 'file not shared' message, and I think that's better than 'scanning shares come back later', as there's a good chance the file hasn't moved.

I'm also contemplating caching share data, but since this is running as a daemon I'm not sure there's a lot of value there.  Perhaps caching, loading the cache on start, and then triggering an asynchronous scan after boot.

I know Nicotine+ caches (or I think I saw that somewhere, anyway); what do you do with requests while the share is being re-scanned?

**Comment by mathiascode** [comment]
> I know Nicotine+ caches (or I think I saw that somewhere, anyway); what do you do with requests while the share is being re-scanned?

Here's what Nicotine+ does:

- Browse share request: keep sending the cached, raw share response. Rebuild it once the scanning process finishes.
  - Sending an empty response here would cause issues SoulseekQt's leech detector if shared files take a long time to scan.
- File download request: temporarily store the incoming message and process it after the scanning process finishes
  - This decision was made mainly for situations where shared files take more than a few seconds to scan at startup, since I don't want to block the UI or server connection until the process has finished. Sending a rejection message always leaves the downloading client in a state where it won't re-request the download automatically.

**Comment by jpdillingham** [comment]
Now that scanning is parallelized, there's not going to be a good way to display the progress of individual directories on the UI that will be user-friendly; directories will be scanned out of order and users might think it was going backwards.

I've increased the process updates to every 5% instead of 10%, and I think I'll probably wind up showing 1% increments, number of scanned and unscanned directories, and maybe an ETA.
