### ISSUE TITLE
Update docs to prefix environment variables with SLSKD_

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#457]
This is an implied prefix described near the top of the document, but I think most people (myself included) tend to scroll to the area of interest and miss it.

**Comment by skar07** [comment]
Please assign this to me. 
Also wanted to understand, does this entail adding prefixes to all the env variables in the config.md with SLSKD_ or only the ones for Soulseek configuration having SLSK_?

**Comment by jpdillingham** [comment]
Yep, you got it.  For example:

This:

| Command-Line             | Environment Variable   | Description                                                   |
| ------------------------ | ---------------------- | ------------------------------------------------------------- |
| `--remote-configuration` | `REMOTE_CONFIGURATION` | Determines whether the remote configuration of options is allowed |

Would become this:

| Command-Line             | Environment Variable   | Description                                                   |
| ------------------------ | ---------------------- | ------------------------------------------------------------- |
| `--remote-configuration` | `SLSKD_REMOTE_CONFIGURATION` | Determines whether the remote configuration of options is allowed |

The ones starting with `SLSK_` would become `SLSKD_SLSKD_`

I think this is going to negatively impact formatting (which is why I avoided this from the start) but I'd rather it be clear to readers.

**Comment by jpdillingham** [comment]
This was closed by #676.  Thanks again!
