### ISSUE TITLE
download notification

### ISSUE THREAD

**Issue by AdSegura** [slskd/slskd#483]
Hi, great software.

Is there any option to execute a script automatically after completing a download?

Thanks.

**Comment by jpdillingham** [comment]
Thanks for asking!

This is on the roadmap under the milestone [0.18: Post-Download Automation](https://github.com/slskd/slskd/milestone/4), specifically in #348 

I'll close this as a duplicate but please don't hesitate to create additional issues if you run into any problems or have additional suggestions.
