### ISSUE TITLE
Downloaded files are owned by root

### ISSUE THREAD

**Issue by kromsam** [slskd/slskd#49]
Because of the way the container is configured, all files created by the container, thus, the downloaded files, are owned by `root`. When dealing with the files later on (playing, moving, renaming), this is pretty unhandy.

It would be great if some sort of user-mapping was implented. As is done with pretty much all linuxserver containers (https://docs.linuxserver.io/general/understanding-puid-and-pgid). Although I don't know how they pull it of.

**Comment by jpdillingham** [comment]
Thanks for raising this, I had noticed but hadn't gotten around to adding it to the roadmap.

**Comment by tge101** [comment]
This would make it work with Lidarr I think.  The only thing I need to adjust is the ownership before Lidarr can process it.

**Comment by jpdillingham** [comment]
This should be fixed in `slskd/slskd:canary` when it pushes in about 20 minutes.  Please give it a shot (run the container with `-u uid:gid`) and let me know!

**Comment by tge101** [comment]
Still seems to be owned by root unfortunately...

**Comment by jpdillingham** [comment]
Can you share your config?  The files should be owned by whatever user you are running the container under.

**Comment by tge101** [comment]
Yea.  I manage through Portainer, so the formatting is a little different.  Maybe the variables are named differently than the conventional way?

version: '2.1'
services:
  web:
    environment:
      - PUID=1000
      - PGID=100
      - "SLSKD_SLSK_USERNAME=username"
      - "SLSKD_SLSK_PASSWORD=pw"
      - "SLSKD_USERNAME=username"
      - "SLSKD_PASSWORD=pw"
      - UMASK_SET=022
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - /srv/dev-disk-by-label-Media/Music/downloads:/var/slskd/downloads
      - /srv/dev-disk-by-label-Media/Music:/var/slskd/shared
    image: slskd/slskd:latest
    restart: always

**Comment by jpdillingham** [comment]
I just tried with `PUID/PGID` set and it didn't seem to do anything.  I tried the same config with `user: 1000:100` (at the compose level) and the downloaded files were owned by the current user.  

Doing some reading (https://docs.linuxserver.io/general/understanding-puid-and-pgid) it seems PUID/PGID are a linuxserver construct that has been superseded by docker's `--user puid:pgid` option, or docker-compose's `user: puid:pgid` directive.

I can look into manually changing the owner of files after they are downloaded if neither of the other methods work, but at first glance there doesn't seem to be a straightforward way to do it that would be cross platform so I'd rather avoid it.

**Comment by dmcallejo** [comment]
I've solved this for now running `docker run` with `--user` or in docker-compose with `user:` . 
Apparently works and I don't see any errors on logs.

**Comment by dchesbro** [comment]
I've tried running the following commands:

```
docker run -d \
  -p 5000:5000 \
  -p 5001:5001 \
  -p 50000:50000 \
  -u $(id -u):$(id -g) \
  -v ~/.docker/slskd:/app \
  -v /mnt/raid/downloads/_s/complete:/downloads \
  -v /mnt/raid/downloads/_s/incomplete:/incomplete \
  --name slskd \
  --restart unless-stopped \
  slskd/slskd:latest
```

and:

```
docker run -d \
  -p 5000:5000 \
  -p 5001:5001 \
  -p 50000:50000 \
  -v ~/.docker/slskd:/app \
  -v /mnt/raid/downloads/_s/complete:/downloads \
  -v /mnt/raid/downloads/_s/incomplete:/incomplete \
  --name slskd \
  --restart unless-stopped \
  --user $(id -u):$(id -g) \
  slskd/slskd:latest
```

but my container just continually restarts. Am I misunderstanding the correct usage here?

**Comment by jpdillingham** [comment]
For the time being, the official guidance for this is to use the `--user`/`user:` functionality described above.

The upcoming post-download automation work will enable users to set permissions explicitly however they like once downloads are complete.

**Comment by tge101** [comment]
> I've solved this for now running `docker run` with `--user` or in docker-compose with `user:` . Apparently works and I don't see any errors on logs.
> 
> An integrated solution would be great, but just FYI

Can you elaborate?  I've had that set to my user and the permissions still stick to root.  I've had an incron job watching the folder but I've noticed that it's been clashing with Lidarr watching the downloads folder too.

**Comment by krestaino** [comment]
> Can you elaborate? I've had that set to my user and the permissions still stick to root. I've had an incron job watching the folder but I've noticed that it's been clashing with Lidarr watching the downloads folder too.

Here's an example using docker compose.

```
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    user: "999:998" # PUID:PGID
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./data:/app
      - /media/downloads/slskd:/app/downloads
    restart: alway
```

**Comment by tge101** [comment]
> > Can you elaborate? I've had that set to my user and the permissions still stick to root. I've had an incron job watching the folder but I've noticed that it's been clashing with Lidarr watching the downloads folder too.
> 
> Here's an example using docker compose.
> 
> ```
> version: "2"
> services:
>   slskd:
>     image: slskd/slskd
>     container_name: slskd
>     user: "999:998" # PUID:PGID
>     ports:
>       - "5030:5030"
>       - "5031:5031"
>       - "50300:50300"
>     environment:
>       - SLSKD_REMOTE_CONFIGURATION=true
>     volumes:
>       - ./data:/app
>       - /media/downloads/slskd:/app/downloads
>     restart: alway
> ```

Ok, so I was trying to set the PGID and PUID incorrectly.  But when I follow this, I get errors in the log that the data directory can't be written to.

**Comment by tge101** [comment]
I am no longer getting errors but the files are still downloading as root

**Comment by jpdillingham** [comment]
Try logging in as the desired user and running `id $USER` to get the `uid` and `gid` values, then substitute them in the config above.

**Comment by toketin** [comment]
Hi, I've added on my compose both the version with `PUID=1000` and `PGID=100`, then the one with `user: "1000:100"`, but my app directory has still been created with root:root ownership. Even deleting itself and restarting again the container it doesn't work. 

This leads to the error: `Directory /app is not writeable`

**Comment by jpdillingham** [comment]
@toketin did you get this resolved?  Sorry I missed this.

**Comment by jpdillingham** [comment]
I'm planning to close this when #1128 is merged; the _user_ config I think has been figured out with `--user` (latest comment notwithstanding), and with the app gaining the ability to explicitly set file permissions for new files it shouldn't matter as much anymore who owns them.

If anyone disagrees, feel free to comment (or reopen once this is closed).

**Comment by TDWillingham** [comment]
Where do we set the option for file permission?  Tried to figure out how to change the --user in Unraid but haven't gotten there yet.

**Comment by jpdillingham** [comment]
@TDWillingham that's coming shortly, see #1128 for details.  I'm going to be doing some final testing and then will release it.
