### ISSUE TITLE
Error while scanning share

### ISSUE THREAD

**Issue by Eric-sson** [slskd/slskd#498]
I am getting this error when scanning my share: Failed to read metadata from file '"/data/media/music/24kGoldn/Single/24kGoldn - Mood (live) (2021) [FLAC]/01-01 - Mood.flac"'; the file is an unsupported format or may be corrupt ("CorruptFileException")

Is this is a known issue?

**Comment by jpdillingham** [comment]
This error means the library that I'm using to get file metadata doesn't know how to process the file.  I'll take a look and see if there needs to be some adjustment so this message isn't so alarming.

**Comment by jpdillingham** [comment]
I changed the warning to a debug statement instead.  I'm not sure what's up with your files that would cause this, but unless this becomes a widespread issue or something I'm just going to leave things as is.  The alternative would be to find a new library for processing the metadata or write my own, neither of which I really want to do.

You can safely ignore these issues; the only downside is that other users on the network won't be able to see the bitrate.

**Comment by mathiascode** [comment]
Logging the exception message would probably be a good idea for debugging the issue.
