### ISSUE TITLE
Simplify share masking and allow sharing of root paths

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#510]
There are a number of shortcomings with handling of shares at the moment, and most are rooted in the way masking is handled.

I wanted to obscure as much of paths as possible to improve privacy, but in doing so I made things difficult to change without creating issues like #420.

I think the correct thing to do is implement a hybrid between the Nicotine+ style of share aliasing ('virtual folders') and Soulseek Qt's masking ('@@abcd').

If an alias is specified for a share, that alias will be the root of that share and all files within it, for example: 

If I share `[Music]C:\Users\JP\Music`, the alias is `Music` and remote users should see `Music\Band\Album\Track.mp3`, even though the physical file is `C:\Users\JP\Music\Band\Album\Track.mp3`.

If no alias is specified, the alias should be the name of the shared folder.  For example:

If I share `C:\Users\JP\Music\Cool Band`, the alias is `Cool Band` and remote users should see `Cool Band\Album\Track.mp3` when the physical file is `C:\Users\JP\Music\Cool Band\Album\Track.mp3`.

Option validation will need to be updated to ensure that aliases can't collide (this may already be the case), as this new configuration has a higher chance of causing collisions and overlap unintentionally.

**Comment by mathiascode** [comment]
What you describe sounds more or less like Nicotine+ works at the moment, if I read your description correctly. Older versions forced the user to specify an alias, but current versions automatically use the name of the folder as the alias (appending a number if the alias is already in use). The user can optionally rename the alias.

**Comment by jpdillingham** [comment]
Good to know! I wasn't sure if the alias was strictly required.  I'm really curious why Qt doesn't do this, too.
