### ISSUE TITLE
"Search again" button doesn't work

### ISSUE THREAD

**Issue by kromsam** [slskd/slskd#513]
An update has brought us the functionality of saving all the searches in a list. This comes in handy because sometimes you want to do the same search again. Although, when I select an old search query, get on its page and click to "Search Again", this doesn't happen. The only thing that happens is that all search results disappear and the "Delete" button becomes a "Stop" button.

I assumed the point was to do a new search for the same query again.

**Comment by jpdillingham** [comment]
Thanks for reporting this; it's a regression.
