### ISSUE TITLE
Feature request: more detailed filter for lossless files

### ISSUE THREAD

**Issue by kromsam** [slskd/slskd#514]
In the "lossless" category there are multiple options for a bit depth/bitrate a file can have. Most .flacs are 16/44. But some are 24/96 or 24/192. It would be nice to have an option to filter in search results for instance all files with 24 bit depth.

**Comment by jpdillingham** [comment]
Thanks for the suggestion.  It should be pretty easy to implement.

**Comment by jpdillingham** [comment]
You can now add the filter keyword `minbitdepth:24` along with `islossless` to achieve this.  Let me know how it works!

**Comment by kromsam** [comment]
Thanks! I'll give it a try when a new release comes out.
