### ISSUE TITLE
Add the ability to blacklist users and IP ranges

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#531]
The application needs a way for users to indicate usernames and potentially entire IP address blocks with which no communication is allowed; no fetching user info or browsing shares, no responding to search requests, and no transfers.

Add a spot somewhere in options to allow an array of usernames and [CIDRs](https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing), then update the code throughout to disallow interaction if a remote user matches anything on the list.

I'm not yet sure how private messaging and chat room messages should be handled.  If a user is blacklisted the client definitely shouldn't accept messages from either source, but there's probably a use case where a user would want to ignore private and/or room messages from someone(s) but not completely blacklist them.

**Comment by jpdillingham** [comment]
The blacklist feature will allow me to avoid scanning shares, so I'm including it in the 0.17 milestone.

**Comment by jpdillingham** [comment]
I'm no longer concerned about the time it takes to retrieve search results from the share cache, so I'm no longer considering this to be related to shares.

This is still something I'd like to add, just in a later milestone.

**Comment by jpdillingham** [comment]
Closed by #741

**Comment by awsms** [comment]
Is it possible to blacklist IP address now?

**Comment by jpdillingham** [comment]
Actually no, I'm glad you asked!  I implemented username blocking in a rush and in doing so completely forgot about IP ranges (CIDRs).  I've reopened this and will add it.

**Comment by samhatter** [comment]
How does this work with chat rooms and messages?
