### ISSUE TITLE
Update UploadQueue.ForecastPosition() to be accurate for round robin type queues

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#543]
Reviewing the implementation of this function this morning, it is clear that it is only accurate for FIFO queues.  Round robin type queues will greatly overstate the estimated position because the logic for FIFO queues is used for them as well.

**Comment by mathiascode** [comment]
As far as I know (to match the behavior of the official client), the queue length values sent in search results and user info responses should be the same, and simply be the total number of queued uploads. If a free slot is available, the value is ignored by the client that receives the search result.
