### ISSUE TITLE
The padding-top property of transfers-header-segment is 20px when it should be 14px

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#554]
This is vertically positioning the buttons correctly, but offsetting the icon by about 6px.  Remove this padding and add `margin-top` for the buttons, or something else, to position them properly.

**Comment by skar07** [comment]
Hey @jpdillingham 
Would love to work on this. Please assign this issue to me under hacktoberfest.

**Comment by jpdillingham** [comment]
Sure thing, thanks!  Just remember to wait until October 1st to submit the PR, or it won't count!

**Comment by jpdillingham** [comment]
Closed by #664 

Thanks again!
