### ISSUE TITLE
Update README with configuration option guidance

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#56]
Per #45, the documentation is a bit lacking in this regard.  Now that the dust has somewhat settled around configuration, update the README (and keep it updated as anything in `Options.cs` changes).

**Comment by tandy-1000** [comment]
Do you need a hand with this? I don't know C# but I can write documentation :)

**Comment by jpdillingham** [comment]
Thanks for the offer!  I could definitely use some help with proofreading and testing.  My goal was to do this this weekend but I distracted myself with other things.  I'm definitely planning to get to it over the holiday.

**Comment by jpdillingham** [comment]
I'm nearing completion of this here: https://github.com/slskd/slskd/blob/docs/docs/config.md

@tandy-1000 A proofread would be appreciated if you've still got the time!

**Comment by tandy-1000** [comment]
Looks good to me!
