### ISSUE TITLE
Completed downloads by users with ? in name cannot be cleared from Web UI

### ISSUE THREAD

**Issue by benzo8** [slskd/slskd#584]
slskd 0.16.8.0 (0.16.8.0-e4644eb), docker-image: slskd/slskd:latest
Ubuntu: 20.04.4 LTS

<img width="845" alt="image" src="https://user-images.githubusercontent.com/3908561/184443975-cd0c1031-af9e-4e2d-91ac-5e445852242c.png">

Remove here does nothing. 

Remove All Succeeded or Remove All Completed pops up an error box for each file by a user with a ? in their username, which says nothing. And doesn't clear anything.

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I'll need to go through and make sure all route parameters for API calls are url encoded.

**Comment by jpdillingham** [comment]
Actually, I think I already url encoded everything.  Remembering back when I worked through this bug with filenames in routes, some characters just can't be properly parsed by ASP.NET, `?` being one of them.  For whatever reason it can't tell the difference between `?` in a route and `?` used to denote query parameters.

**Comment by jpdillingham** [comment]
I was wrong, a few API calls had not yet been encoded, including the one to delete files.

**Comment by jpdillingham** [comment]
Also recalling the issue with filenames in routes; the character for which there is no workaround is `/`, which makes sense.  There may still be something that can be done with double-escaping, but it's a non-issue now.
