### ISSUE TITLE
Consider using another default port (macOS related)

### ISSUE THREAD

**Issue by ldexterldesign** [slskd/slskd#594]
https://medium.com/pythonistas/port-5000-already-in-use-macos-monterey-issue-d86b02edd36c

Excuse terseness 😘

Sincerely

**Comment by jpdillingham** [comment]
Based on the [IANA registry](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=&skey=-7&page=88) and a quick Google search, port 5030 seems to be free of conflict.

My thinking is that 5030 was registered in 2006 but de-registered last year, so there's a good chance nothing important is using it now.

**Comment by ldexterldesign** [comment]
Thanks for reply

Seems a convenient enhancement to me and should save some config headaches for macOS users

I did some quick research and it seems Apple is still hijacking port 5000 in the latest macOS so unlikely to change 🤷

Aside, interesting to know about the IANA stuff - I always wonder how creators choose/consider their port choices (probably little consideration!)

Cheers
