### ISSUE TITLE
"Exception of type 'System.OutOfMemoryException' was thrown when scanning exceptionally large shares

### ISSUE THREAD

**Issue by khalimerot** [slskd/slskd#610]
Hi, 
Each time i'm trying to scan one of my shared folder i got this error after a few minutes (between 20 & 30% of the scan) 

```
22:02:21	ERR	An unhandled exception has occurred while executing the request.
22:02:21	WRN	Encountered error during scan of shared files: "Exception of type 'System.OutOfMemoryException' was thrown.
22:02:21	ERR	Failed to scan shares.
```

I already have split the scan in multiple part, but this folder have +/- 700k files.

My server is a 64GB RAM, SLSKD is running in a docker, on Unraid.
I don't think I have a RAM limitation on this docker, and the RAM of the server is not full.

Scanning the same folders with realies/soulseek docker worked well, even if it was very long.

Any idea on how i can solve the problem? 

Thank you!

**Comment by jpdillingham** [comment]
Thanks for reporting this.  Does the application continue running after this?

If you [enable debugging] by setting `DEBUG=true` in the envars for the container you should get a more detailed error, but I'll push up an update that will improve this shortly and you can just update instead.

**Comment by khalimerot** [comment]
Here is the log with the debug: 


```
17:52:27 | WRN | Encountered error during scan of shared files: "Exception of type 'System.OutOfMemoryException' was thrown.
17:52:27 | ERR | Failed to scan shares.
17:52:27 | INF | Scanned 0% of shared directories.  Found 548944 files so far.
17:39:48 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Modland/Jamsam/mod.el4_T01_ORG.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
17:32:09 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Games/Spider-Man_02/mod.gmour_T01_MIX.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
17:32:09 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Games/Spider-Man_02/mod.action_T01_MIX.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
17:32:09 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Games/Spider-Man_01/mod.succ_T01_MIX.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
17:25:31 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/Commodor/MUSICIANS/J/JO/Quick_Kill_T01.sid_CSG8580R5.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
17:20:23 | INF | Scanned 20% of shared directories.  Found 226259 files so far.
17:13:58 | INF | Scanned 10% of shared directories.  Found 150395 files so far.
17:06:32 | DBG | Failed  to read metadata from file '"/shared/Divers - various/The Smashing  Pumpkins/Singles/Zero (1996)/06 - Pennies.flac"'; the file is an  unsupported format or may be corrupt ("CorruptFileException")
17:04:15 | DBG | Failed  to read metadata from file '"/shared/Divers - various/Two Steps From  Hell/Singles/2015 - Thomas Bergersen - You Are Light (feat. Felicia  Farerre)/01. You Are Light (feat. Felicia Farerre).flac"'; the file is  an unsupported format or may be corrupt ("CorruptFileException")
16:59:49 | DBG | Failed  to read metadata from file '"/shared/Divers - various/Kraftwerk/1991 -  Die Roboter/B02 Robotronik (Kling Klang Mix).flac"'; the file is an  unsupported format or may be corrupt ("CorruptFileException")
16:57:36 | DBG | Found 491039 shared directories (and 0 were excluded) in 558029ms.  Starting file scan.
16:49:05 | INF | Disconnected from the Soulseek server: disconnected by the user
16:48:18 | INF | Logged in to the Soulseek server as "Khalimerot
16:48:18 | INF | Version "0.16.17.0" is up to date.
16:48:18 | INF | Connected to the Soulseek server
16:48:18 | DBG | Enumerating shared directories
16:48:18 | INF | Sharing "/shared/Film - movie" as "Film - movie
16:48:18 | INF | Sharing "/shared/Jeux - games" as "Jeux - games
16:48:18 | INF | Sharing "/shared/Stone Oakvalley" as "Stone Oakvalley
16:48:18 | INF | Sharing "/shared/Divers - various" as "Divers - various
16:48:18 | INF | Sharing "/shared/Anime & TV - Comics & TV" as "Anime & TV - Comics & TV
16:48:18 | DBG | {"id":"034BE14093B7A38AACAC28A8F6FDA8370E457865","alias":"Film  - movie","isExcluded":false,"localPath":"/shared/Film -  movie","raw":"/shared/Film - movie","remotePath":"Film - movie"}
16:48:18 | DBG | {"id":"6B2549859205D6CEF7AA25117F7045AB84731E7F","alias":"Jeux  - games","isExcluded":false,"localPath":"/shared/Jeux -  games","raw":"/shared/Jeux - games","remotePath":"Jeux - games"}
16:48:18 | DBG | {"id":"7F0F90856330CAD42BE4643A63353EC4C09D60BD","alias":"Stone  Oakvalley","isExcluded":false,"localPath":"/shared/Stone  Oakvalley","raw":"/shared/Stone Oakvalley","remotePath":"Stone  Oakvalley"}
16:48:18 | DBG | {"id":"CDD57F87959B4D8FCDD501368EFC0B4C7C73BF09","alias":"Divers  - various","isExcluded":false,"localPath":"/shared/Divers -  various","raw":"/shared/Divers - various","remotePath":"Divers -  various"}
16:48:18 | DBG | {"id":"4EAFC10BCAD0270E3674F06A266A3B97DB252985","alias":"Anime  \u0026 TV - Comics \u0026  TV","isExcluded":false,"localPath":"/shared/Anime \u0026 TV - Comics  \u0026 TV","raw":"/shared/Anime \u0026 TV - Comics \u0026  TV","remotePath":"Anime \u0026 TV - Comics \u0026 TV"}
16:48:18 | DBG | Starting shared file scan
16:48:18 | INF | Scanning shares
```

The disconnect is normal it's because i needed to reconnect the other soulseek docker i have.

The app continue to work after this error, all share are gone.

i'll wait for the update, thank you!

**Comment by khalimerot** [comment]
I have corrected somes files, and put some other i couldn't correct (source is corrupted) in the ignore list.
It still crash and see the few same last corrupted file.

The strange part is that it doesn't crash immediatly after the laste corrupted file, but 8 min later, and during these 8 minutes i ear my nas working and stoping right after the crash.

So if it's a file problem, slskd doesn't tell me wich file is causing it.

`
20:08:05 | DBG | Filters.Share  changed from  '["\\.ini$","Thumbs.db$","\\.DS_Store$","mod.el4_T01_ORG.mp3$","mod.gmour_T01_MIX.mp3$","mod.action_T01_MIX.mp3$","mod.succ_T01_MIX.mp3$"]'  to  '["\\.ini$","Thumbs.db$","\\.DS_Store$","mod.el4_T01_ORG.mp3$","mod.gmour_T01_MIX.mp3$","mod.action_T01_MIX.mp3$","mod.succ_T01_MIX.mp3$","Quick_Kill_T01.sid_CSG8580R5.mp3$"]'`

`21:14:23 | ERR | An unhandled exception has occurred while executing the request.
-- | -- | --
21:14:23 | WRN | Encountered error during scan of shared files: "Exception of type 'System.OutOfMemoryException' was thrown.
21:14:23 | ERR | Failed to scan shares.
21:14:23 | INF | Scanned 0% of shared directories.  Found 546213 files so far.
21:06:50 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Modland/Jamsam/mod.el4_T01_ORG.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
21:02:25 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Games/Spider-Man_02/mod.gmour_T01_MIX.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
21:02:25 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Games/Spider-Man_02/mod.action_T01_MIX.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
21:02:25 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/AMIGA/soamc/soamc_mp3/Trackers_Games/Spider-Man_01/mod.succ_T01_MIX.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")
20:58:08 | DBG | Failed  to read metadata from file '"/shared/Stone  Oakvalley/Commodor/MUSICIANS/J/JO/Quick_Kill_T01.sid_CSG8580R5.mp3"';  the file is an unsupported format or may be corrupt  ("CorruptFileException")`

**Comment by jpdillingham** [comment]
The 0% message after the scan has obviously progressed past that makes me believe that the out of memory exception is coming from an integer overflow rather than a memory problem.  Usually if the app actually runs out of memory it will crash, also.  

I'll deploy a change this evening to surface the stack trace of the OOM Exception in the UI, that should give a clear view of what's happening.

**Comment by jpdillingham** [comment]
The fix for logging was merged in #611.  I've created release [0.16.18](https://github.com/slskd/slskd/releases/tag/0.16.18) and a new container image should be ready at the `latest` tag about 30 minutes from this post.

**Comment by khalimerot** [comment]
Here is the error after the update 

`06:48:10 | WRN | Encountered error during scan of shared files: "Exception of type 'System.OutOfMemoryException' was thrown.": System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at System.Array.InternalCreate(Void* elementType, Int32 rank, Int32* pLengths, Int32* pLowerBounds) at System.Array.CreateInstance(Type elementType, Int32 length) at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit) at System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.GetFSharpCoreAssembly(Type type) at System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.IsFSharpType(Type type) at System.Text.Json.Serialization.Converters.FSharpTypeConverterFactory.CanConvert(Type typeToConvert) at System.Text.Json.JsonSerializerOptions.GetConverterInternal(Type typeToConvert) at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo) at System.Text.Json.Serialization.Metadata.JsonTypeInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options) at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo\|112_0(Type type, JsonSerializerOptions options) at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type) at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.get_RuntimeTypeInfo() at System.Text.Json.ReadStack.Push() at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader) at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount) at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo) at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) at slskd.ManagedState`1.SetValue(Func`2 setter) at slskd.Shares.SharedFileCache.FillAsync(IEnumerable`1 shares, IEnumerable`1 filters)
-- | -- | --
06:48:10 | ERR | Failed to scan shares.
`

**Comment by jpdillingham** [comment]
Thanks for following up! This seems pretty obscure; I'll have to do some digging.

Formatted:

```
Encountered error during scan of shared files: "Exception of type 'System.OutOfMemoryException' was thrown.": System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. 
    at System.Array.InternalCreate(Void* elementType, Int32 rank, Int32* pLengths, Int32* pLowerBounds) at System.Array.CreateInstance(Type elementType, Int32 length) 
    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit) 
    at System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.GetFSharpCoreAssembly(Type type) 
    at System.Text.Json.Serialization.Metadata.FSharpCoreReflectionProxy.IsFSharpType(Type type) 
    at System.Text.Json.Serialization.Converters.FSharpTypeConverterFactory.CanConvert(Type typeToConvert) 
    at System.Text.Json.JsonSerializerOptions.GetConverterInternal(Type typeToConvert) 
    at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo) 
    at System.Text.Json.Serialization.Metadata.JsonTypeInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options) 
    at System.Text.Json.JsonSerializerOptions.g__CreateJsonTypeInfo|112_0(Type type, JsonSerializerOptions options) 
    at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type) 
    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.get_RuntimeTypeInfo() 
    at System.Text.Json.ReadStack.Push() 
    at System.Text.Json.Serialization.JsonConverter1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) 
    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader) 
    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) 
    at System.Text.Json.Serialization.JsonConverter1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) 
    at System.Text.Json.Serialization.JsonConverter1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) 
    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable1 actualByteCount) 
    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan1 json, JsonTypeInfo jsonTypeInfo) at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options) 
    at slskd.ManagedState1.SetValue(Func2 setter) at slskd.Shares.SharedFileCache.FillAsync(IEnumerable1 shares, IEnumerable1 filters)
```

**Comment by jpdillingham** [comment]
I've just merged #612 which adds debug logging before and after each scanned directory.  This will allow us to see if a specific directory is causing the problem.

You should start seeing logs like the following for each shared directory:

```
09:01:13	DBG	Finished scanning "\\share\folder": 4 files added and 0 filtered
09:01:13	DBG	Starting scan of "\\share\folder" (91/92)
```

I've also removed a property from the internal cache state that represented the list of shares that had been scanned.  This property was being copied and re-allocated at least twice each time the state was updated, which could easily cause or amplify memory pressure.

This change should be out with the `canary` tag about 30 minutes from now.  If switching to the canary is a hassle please let me know and I can create a release, I'm just avoiding it because of the thrashing going on lately.

**Comment by khalimerot** [comment]
It's the stone oakvalley folder that is causing the problem.

i scaned the others folder idependantly

**Comment by jpdillingham** [comment]
Thanks for following up.  If you exclude that directory does the scan complete?

A large number of subfolders shouldn't break anything with the scan, at least logically.  All directories are enumerated first, and then each is scanned by itself (no recursion), so theoretically you could have a structure as deep as the operating system will allow.

Do any of these subdirectories have a large amount of files?

**Comment by khalimerot** [comment]
Stone Oakvalley share is : 415.588 files in 23.440 folders, for a total of 1.03TB
The others share combined are : 137.232 files in 12.454 folders, for a total of 2.68TB
    - /shared/Anime & TV - Comics & TV
    - /shared/Jeux - games
    - /shared/Film - movie
    - /shared/Divers - various
(counted by windows)
SLSKD give me 149380 shared directories after a new scan (this number is odly high)
(Stone Oakvalley is still mounted in the docker, but not in the shared configuration)

When scanning only : 
    - /shared/Anime & TV - Comics & TV
    - /shared/Jeux - games
    - /shared/Film - movie
    - /shared/Divers - various
I have this result : 
```
17:24:43 | ERR | An  unhandled exception has occurred while executing the request.:  System.OutOfMemoryException: Exception of type  'System.OutOfMemoryException' was thrown.    at Soulseek.File.GetAttributeValue(FileAttributeType type)    at Soulseek.File..ctor(Int32 code, String filename, Int64 size,  String extension, IEnumerable`1 attributeList)    at  slskd.Shares.SharedFileCache.<>c.<Browse>b__31_3(KeyValuePair`2  g)    at System.Linq.Enumerable.SelectIListIterator`2.ToList()    at Soulseek.Directory..ctor(String name, IEnumerable`1 fileList)    at  slskd.Shares.SharedFileCache.<>c.<Browse>b__31_1(IGrouping`2  g)    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()    at slskd.Shares.SharedFileCache.Browse()    at slskd.Shares.ShareService.BrowseAsync()    at slskd.Shares.API.SharesController.List()    at  Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper  mapper, ObjectMethodExecutor executor, Object controller, Object[]  arguments)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker  invoker, ValueTask`1 actionResultValueTask)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker  invoker, Task lastTask, State next, Scope scope, Object state, Boolean  isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed  context)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&  next, Scope& scope, Object& state, Boolean& isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location ---    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited\|25_0(ResourceInvoker  invoker, Task lastTask, State next, Scope scope, Object state, Boolean  isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed  context)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&  next, Scope& scope, Object& state, Boolean& isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location ---    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker  invoker, Task task, IDisposable scope)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker  invoker, Task task, IDisposable scope)    at  Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint  endpoint, Task requestTask, ILogger logger)    at  Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate  next, HttpContext context, AuthorizationPolicy policy,  PolicyAuthorizationResult authorizeResult)    at  Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext  context)    at  Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext  context)    at slskd.HTMLInjectionMiddleware.InvokeAsync(HttpContext context)    at slskd.HTMLRewriteMiddleware.InvokeAsync(HttpContext context)    at  Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited\|6_0(ExceptionHandlerMiddleware  middleware, HttpContext context, Task task)
17:24:37 | DBG | Shared file cache recreated in 2480276ms.  Directories: 149380, Files: 323679
17:24:37 | INF | Shares scanned successfully. Found 149380 directories and 323679 files in 2480315.9012ms
17:24:37 | DBG | Inserted 323679 records in 26959ms
17:24:10 | DBG | Directory scan found 323679 files (and 79 were filtered) in 2327933ms.  Populating filename database
17:24:05 | INF | Scanned 100% () of shared directories.  Found 322775 files so far.
17:20:23 | INF | Scanned 90% () of shared directories.  Found 294916 files so far.
17:15:39 | INF | Scanned 80% () of shared directories.  Found 266740 files so far.
17:09:14 | INF | Scanned 70% () of shared directories.  Found 236144 files so far.
17:07:24 | INF | Scanned 60% () of shared directories.  Found 218764 files so far.
17:05:30 | INF | Scanned 50% () of shared directories.  Found 196345 files so far.
17:03:32 | INF | Scanned 40% () of shared directories.  Found 172687 files so far.
17:01:29 | INF | Scanned 30% () of shared directories.  Found 146580 files so far.
16:58:51 | INF | Scanned 20% () of shared directories.  Found 115072 files so far.
16:55:50 | INF | Scanned 10% () of shared directories.  Found 79955 files so far.
16:45:22 | DBG | Found 149380 shared directories (and 0 were excluded) in 125314ms.  Starting file scan.
16:43:17 | DBG | Enumerating shared directories
16:43:17 | INF | Sharing "/shared/Film - movie" as "Film - movie
16:43:17 | INF | Sharing "/shared/Jeux - games" as "Jeux - games
16:43:17 | INF | Sharing "/shared/Divers - various" as "Divers - various
16:43:17 | INF | Sharing "/shared/Anime & TV - Comics & TV" as "Anime & TV - Comics & TV

```

There was a few corrupted metada between 80 & 90% i removed it from logs for readability
The error show when i tried to access the shares tab to see if everything was ok : 

![image](https://user-images.githubusercontent.com/20107904/186459494-61540b09-7933-4713-8824-93276b469930.png)

**Comment by jpdillingham** [comment]
I've just created a new release with a couple of small tweaks in it to help surface the issues (and maybe help with memory consumption), so you might try that once it is ready in ~30 minutes.

I think it is pretty clear at this point that slskd can't handle this many files.  The out of memory exception is moving around to different allocation points which means it's just running out of memory.

The next milestone, [0.17: Share Scanning at Scale](https://github.com/slskd/slskd/milestone/5) will be addressing this indirectly, but what we're seeing here is an issue with how data is stored in memory, not how it is scanned.

Unfortunately there's no quick fix, as I have to completely rewrite how sharing works.

**Comment by jpdillingham** [comment]
I guess one thing we haven't discussed is whether there's a hard or soft limit on the container hosting the app.  I wouldn't expect this many files to max out 64gb, so I think there's either some sort of practical limit within the .NET runtime (which would be news to me but not impossible) or there's something preventing you from being able to access more memory.

Could you try running slskd with the same shares configured on bare metal, outside of docker? This would be a quick way to rule this out.

**Comment by khalimerot** [comment]
from my computer (windows 11/ 32gb RAM) with the drive mounted  : 


19:25:10 | DBG | Shared file cache recreated in 1775640ms.  Directories: 12454, Files: 137083
-- | -- | --
19:25:10 | INF | Shares scanned successfully. Found 12454 directories and 137083 files in 1775697.5976ms
19:25:10 | DBG | Inserted 137083 records in 4857ms
19:25:05 | DBG | Directory scan found 137083 files (and 33 were filtered) in 1732237ms.  Populating filename database
19:24:59 | INF | Scanned 100% () of shared directories.  Found 136374 files so far.
19:20:21 | INF | Scanned 90% () of shared directories.  Found 116619 files so far.
19:17:06 | INF | Scanned 80% () of shared directories.  Found 99651 files so far.
19:16:00 | INF | Scanned 70% () of shared directories.  Found 89599 files so far.
19:15:19 | INF | Scanned 60% () of shared directories.  Found 79272 files so far.
19:11:00 | INF | Scanned 50% () of shared directories.  Found 63830 files so far.
19:09:01 | INF | Scanned 40% () of shared directories.  Found 51867 files so far.
19:09:00 | ERR | Disconnected from the Soulseek server: another client logged in using the same username
19:09:00 | DBG | Kicked from server.
19:05:46 | INF | Scanned 30% () of shared directories.  Found 37555 files so far.
19:01:25 | INF | Scanned 20% () of shared directories.  Found 22659 files so far.
18:58:21 | INF | Scanned 10% () of shared directories.  Found 8941 files so far.
18:56:13 | DBG | Found 12454 shared directories (and 0 were excluded) in 38492ms.  Starting file scan.
18:55:35 | INF | Logged in to the Soulseek server as "Khalimerot
18:55:35 | INF | Connected to the Soulseek server
18:55:35 | INF | A new version is available! "0.16.18.0" -> "0.16.19
18:55:34 | DBG | Enumerating shared directories
18:55:34 | INF | Sharing "x:\Film - movie" as "Film - movie
18:55:34 | INF | Sharing "x:\Jeux - games" as "Jeux - games
18:55:34 | INF | Sharing "x:\Divers - various" as "Divers - various
18:55:34 | INF | Sharing "x:\Anime & TV - Comics & TV" as "Anime & TV - Comics & TV

Everything seems ok : 

![image](https://user-images.githubusercontent.com/20107904/186484905-08fa84e6-2266-47cc-8750-24a1af1644db.png)

And the share folder count seems correct this time.

I don't know if the memory limitation come from docker, but i don"t have any problem to scan folders with Realies/slsk docker.

**Comment by khalimerot** [comment]
Docker updated , folder rescanned 


```
21:33:38 | ERR | An  unhandled exception has occurred while executing the request.:  System.OutOfMemoryException: Exception of type  'System.OutOfMemoryException' was thrown.    at  slskd.Shares.SharedFileCache.<>c.<Browse>b__31_1(IGrouping`2  g)    at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()    at slskd.Shares.SharedFileCache.Browse()    at slskd.Shares.ShareService.BrowseAsync()    at slskd.Shares.API.SharesController.List()    at  Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper  mapper, ObjectMethodExecutor executor, Object controller, Object[]  arguments)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited\|12_0(ControllerActionInvoker  invoker, ValueTask`1 actionResultValueTask)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited\|10_0(ControllerActionInvoker  invoker, Task lastTask, State next, Scope scope, Object state, Boolean  isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed  context)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State&  next, Scope& scope, Object& state, Boolean& isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync() --- End of stack trace from previous location ---    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited\|25_0(ResourceInvoker  invoker, Task lastTask, State next, Scope scope, Object state, Boolean  isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed  context)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State&  next, Scope& scope, Object& state, Boolean& isCompleted)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location ---    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker  invoker, Task task, IDisposable scope)    at  Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited\|17_0(ResourceInvoker  invoker, Task task, IDisposable scope)    at  Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask\|6_0(Endpoint  endpoint, Task requestTask, ILogger logger)    at  Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate  next, HttpContext context, AuthorizationPolicy policy,  PolicyAuthorizationResult authorizeResult)    at  Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext  context)    at  Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext  context)    at slskd.HTMLInjectionMiddleware.InvokeAsync(HttpContext context)    at slskd.HTMLRewriteMiddleware.InvokeAsync(HttpContext context)    at  Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited\|6_0(ExceptionHandlerMiddleware  middleware, HttpContext context, Task task)
21:33:23 | DBG | Shared file cache recreated in 1825745ms.  Directories: 149380, Files: 323679
21:33:23 | INF | Shares scanned successfully. Found 149380 directories and 323679 files in 1825773.1502ms
21:33:23 | DBG | Inserted 323679 records in 29164ms
21:32:54 | DBG | Directory scan found 323679 files (and 79 were filtered) in 1674459ms.  Populating filename database
21:32:54 | DBG | Finished scanning "/shared/Film - movie": 0 files added and 0 filtered
21:32:54 | DBG | Starting scan of "/shared/Film - movie" (149380/149380)
21:32:54 | DBG | Finished scanning "/shared/Jeux - games": 0 files added and 0 filtered
21:32:54 | DBG | Starting scan of "/shared/Jeux - games" (149379/149380)
21:32:54 | DBG | Finished scanning "/shared/Divers - various": 0 files added and 0 filtered
21:32:54 | DBG | Starting scan of "/shared/Divers - various" (149378/149380)
21:32:54 | DBG | Finished scanning "/shared/Anime & TV - Comics & TV": 0 files added and 0 filtered
21:32:54 | DBG | Starting scan of "/shared/Anime & TV - Comics & TV" (149377/149380)
```
I saw each file being scanned, so the more verbose log works.
Scan goes to 100%, but when i want to see the share tab, i got this error.

**Comment by jpdillingham** [comment]
Thanks for all this additional info, it's very helpful.

I'll investigate whether there's a memory limitation in Docker that I'm unaware of; I'd expect it to allow containers to use all available memory on the machine but that might not be the case based on these results.

> i don"t have any problem to scan folders with Realies/slsk docker.

I think the way slskd stores shares in memory is probably extremely inefficient compared to other clients, unfortunately.

**Comment by khalimerot** [comment]
Complementary information, 
Even with the error SLSKD respond to search, and my files appear, and can be downloaded 

![image](https://user-images.githubusercontent.com/20107904/188872045-68d90121-b8cc-41f1-a4a8-961c998d8f5b.png)

But my library cannot be browsed : 

[Soulseek.Messaging.Handlers.PeerMessageHandler] [13:49:12 WRN] Error handling peer message: BrowseRequest from khalimerot2 (IP:61538); Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by jpdillingham** [comment]
@khalimerot did you have a chance to try out the [latest release](https://github.com/slskd/slskd/releases/tag/0.16.22)? It includes a bunch of improvements to shares, and will allow you to choose to store the cache on disk.

I added this ability to make the application work with large shares such as yours, so I'd be grateful if you could try it and let me know how it goes!

**Comment by khalimerot** [comment]
Hi, 
i did try it a few days ago, and didn't saw the new options with cache on disk and workers.
Thank to poiting it to me.

I'm trying it now.
It seems to work well, it's relativilely slower but it's ok for me, i'm not hurry.
I don't know if it's linked to that, but when i start the docker, the http page is also significantly slower to be available. 
I have to wait +/-2 min before the http login page appear, but again, i'm not in a hurry, so it's ok, when you know you have to wait :)

**Comment by jpdillingham** [comment]
A lot has changed since the last post on this issue, so I'm going to close it.  @khalimerot feel free to re-open if you're still having problems.
