### ISSUE TITLE
Search filter 'minbitdepth' includes files with no bit depth unless `islossless` is also specified

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#625]
Search for anything, then enter 'minbitdepth:24`.  I'd expect only lossless files with bit depth of 24 to show up, and instead it appears as though no filter is applied at all.

Setting `minbitdepth:5000` does not change anything.  It appears as though this is completely broken.

**Comment by mattgoldspink** [comment]
Just wanted to say I looked into this and it seems to work correctly for me. If a flac file comes back with 24 bitdepth I can see it being filtered correctly.

**Comment by jpdillingham** [comment]
I took another look this morning, and I think the issue is that it includes results that don't specify a bit depth at all.  

To get the expected behavior (well, expected is debatable and the root of this issue), you have to also specify `islossless`.

I think `minbitdepth` implies `islossless`, but because they are two different filters, I think I didn't make that association in the code.  I think I should have because it tripped me up, and I think the same could be assumed for other users.

**Comment by jpdillingham** [comment]
Per #624 this is working as well as it can.
