### ISSUE TITLE
Add an option for incomplete download path

### ISSUE THREAD

**Issue by mattgoldspink** [slskd/slskd#64]
Firstly - thanks for the awesome project! Been running it for a month now and it's great.

One feature I'd love to see is a separate location for inprogress downloads, and then move them to the downloads folder when complete. I'd like to be able to set up watchers on the download folder that auto tag and move the files, but at the moment it's not possible because it doesn't know whether the file has been completely downloaded or not.

**Comment by jpdillingham** [comment]
Thanks for raising this, this is near the top of my list also.
