### ISSUE TITLE
Builds fail if the short commit SHA of the head is only numbers

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#642]
```
/home/runner/.dotnet/sdk/6.0.100/NuGet.targets(130,5): error : '0.16.21.65534-0146571' is not a valid version string. (Parameter 'value') [/home/runner/work/slskd/slskd/src/slskd/slskd.csproj]
```

This is a shortcoming of .NET tooling; it doesn't want to see a numeric suffix here.  I believe the rationale is that they expect this to be something like `-beta` or `-rc1`, so sticking the SHA here is a little unorthodox (though it shouldn't be).

When this happens I have to push an empty commit to either the feature branch or master to get it resolved.  It's pretty rare, but also pretty annoying.

**Comment by Exouxas** [comment]
Wouldn't this go against SemVers 2? According to the SemVers 2 spec, you're supposed to use `+` when adding metadata like the hash https://semver.org/spec/v2.0.0.html#spec-item-10

I might be completely wrong though, and there could be issues with backward compatibility if you use the versioning for something.

**Comment by jpdillingham** [comment]
You're right! I wasn't aware that I should have been using `+`.  I tested this locally, and `0.16.21.65534-0146571` is still breaking, while `0.16.21.65534+0146571` isn't, so this would fix both issues.

The only other change that should be needed is the `Split` [here](https://github.com/slskd/slskd/blob/master/src/slskd/Program.cs#L134)

**Comment by Exouxas** [comment]
I'll change it right away!

Also I see you've added a contribution guideline since last time I contributed. Would you like the branch to be created on this repo or a fork?

And lastly, I'm having a hard time finding where you set the version string for compilation, could I have some assistance there?

**Comment by jpdillingham** [comment]
A fork is best, and you've found the right script!
