### ISSUE TITLE
Scanning shares seems to be stuck on 100%

### ISSUE THREAD

**Issue by moondownr** [slskd/slskd#651]
Updated to 0.16.21 from 0.16.17.

Scanning shares reached 100% 1.5 hours ago. 

`23:30:50 | INF | Scanned 100% of shared directories. Found 61177 files so far.`

"Pending Action" and "Shares" still display yellow exclamation mark, in the Shares there is still a spinner over "100%". No new log messages. RAM usage is slowly climbing (almost up to 1GB now). Something is constantly being written to disk by slskd at about 50-500kb/s (looking at glances output).

Is this normal?

**Comment by moondownr** [comment]
As I was writing the issue, the RAM usage dropped to 600MB

**Comment by moondownr** [comment]
Still the same situation, beginning to think the scan will never register as 'completed'.

**Comment by jpdillingham** [comment]
It should only take a few seconds to finish after it hits 100%, regardless of version.

Which version is this?z

**Comment by moondownr** [comment]
`Updated to 0.16.21 from 0.16.17.`

Might be be something connected with
`Store shared file cache on disk instead of memory`

**Comment by jpdillingham** [comment]
With 16.21 the code will save all of the found files to an SQLite database located on disk; there may be something about your system that is making this extremely slow, or causing it to error in a weird way that isn't surfacing.

I just created a new release for [0.16.22](https://github.com/slskd/slskd/releases/tag/0.16.22) which defaults back to using in-memory storage and makes a few other improvements.  The binaries and Docker container should be ready about 30 minutes from this post, please give it a try and let me know if you're still experiencing issues.

Nothing has really changed in this release with respect to on-disk storage, so there may still be a bug there.  Can you share more about your system? OS, type of hardware, and whether you're using Docker, primarily.

**Comment by moondownr** [comment]
All the info is here https://github.com/slskd/slskd/issues/598#issuecomment-1220143407

I let it run south of 3 hours that last time, at which point I shut it off. Haven't been using slskd since.

**Comment by jpdillingham** [comment]
Thanks for the reminder, I thought we'd had a similar conversation before.  It seems like SQLite runs very poorly on your system, so this behavior is not that surprising given the amount of disk I/O at the end of the scan.  The 0.16.22 release should hopefully fix the issue as long as you leave the cache `storage_mode` option set to `memory`.

**Comment by jpdillingham** [comment]
I should note that while developing the changes to store the share cache on disk I was benchmarking on a Raspberry Pi 2 with 32 bit Ubuntu Server running from a 32gb SD card; what I felt would be the worst case scenario.  I think this means that for whatever reason, my SQLite implementation runs remarkably poorly on btrfs.  I'll create a separate issue to see if I can replicate this and if so, find a workaround.

**Comment by moondownr** [comment]
Noticed something peculiar, not sure how relevant it is.

> вер 20 16:33:46 minimoon slskd[799417]: [16:33:46 WRN] Failed to invoke QueueDownload action: Object reference not set to an instance of an o>
вер 20 16:33:50 minimoon slskd[799417]: [16:33:50 INF] Sharing /mnt/nfs/hd1/Music_Archive as Music_Archive
вер 20 16:33:50 minimoon slskd[799417]: [16:33:50 INF] Sharing /mnt/nfs/hd1/Library as Library
вер 20 16:33:50 minimoon slskd[799417]: [16:33:50 INF] Sharing /mnt/nfs/hd1/Music as Music
вер 20 16:33:50 minimoon slskd[799417]: [16:33:50 WRN] Failed to scan share /mnt/nfs/hd1/Music_Archive: Could not find a part of the path '/m>

This is from earlier today, when I attempted a new scan. It still never made it past 100% in UI. 
Now, the "/mnt/nfs/hd1/Music_Archive" doesn't exist (hasn't been there for months), but I forgot to edit share list for slskd. Never caused issues before, but I decided to remove it and try rerunning scan again.
Still stuck at 100%, but this time I notice in logs:

> 
> вер 20 19:05:44 minimoon slskd[801654]: [19:05:44 INF] [UPLOAD REQUESTED] jonhyboomer requested @@quzqt/Music_Archive/El Ritual/1971 - El Ritual\cd.jpg
> вер 20 19:05:44 minimoon slskd[801654]: [19:05:44 INF] [UPLOAD REJECTED] jonhyboomer for @@quzqt/Music_Archive/El Ritual/1971 - El Ritual\cd.jpg: file not found
> вер 20 19:05:44 minimoon slskd[801654]: [19:05:44 INF] [UPLOAD REQUESTED] jonhyboomer requested @@quzqt/Music_Archive/El Ritual/1971 - El Ritual\front.jpg
> вер 20 19:05:44 minimoon slskd[801654]: [19:05:44 INF] [UPLOAD REJECTED] jonhyboomer for @@quzqt/Music_Archive/El Ritual/1971 - El Ritual\front.jpg: file not found
> вер 20 19:05:44 minimoon slskd[801654]: [19:05:44 INF] [UPLOAD REQUESTED] jonhyboomer requested @@quzqt/Music_Archive/El Ritual/1971 - El Ritual\inside.jpg
> вер 20 19:05:44 minimoon slskd[801654]: [19:05:44 INF] [UPLOAD REJECTED] jonhyboomer for @@quzqt/Music_Archive/El Ritual/1971 - El Ritual\inside.jpg: file not found
> 

There were multiple slskd restarts and updates between me moving the Music_Archive folder to a different location and now. As far as I understand, slskd shouldn't be even aware of any path under /Music_Archive, despite it being listed in shares until today - there was nothing to scan there. So how come someone is attempting to download something from the old path?

**Comment by jpdillingham** [comment]
I'm not sure what causes other clients to keep attempting these when they've gotten a `file not found` response in the past, but it happens from time to time.

Earlier today I realized that while the other SQLite databases have WAL mode enabled by default, the one backing the shares doesn't, since it is created through another mechanism.  I'll push a change later tonight that enables it and ensures it is set at startup, that should help when the storage mode is set to `disk`.

Did you get a chance to try out the latest version? It will store the cache in memory by default.  There's a breaking change in the config, though, which you can read about [here](https://github.com/slskd/slskd/releases/tag/0.16.22).

**Comment by moondownr** [comment]
Sorry for the long wait. Just updated to 0.16.22 today, problem is non-existent with memory cache (as expected).

**Comment by jpdillingham** [comment]
Thanks for following up! Glad it's working for you.

**Comment by mathiascode** [comment]
> I'm not sure what causes other clients to keep attempting these when they've gotten a `file not found` response in the past, but it happens from time to time.

Most likely due to restarting their client, since unfinished downloads are queued again.
