### ISSUE TITLE
Folders Filters

### ISSUE THREAD

**Issue by khalimerot** [slskd/slskd#665]
Hi,

Would it be possible to have a filter based on folder names? 

Taking myself as an example, each of my folders have an @eaDir subfolders generated by my synology.

This folders is not meant to be shared, and is useless outside of synology app.

It would be nice to not have them showed in SLSKD, so users who take complete folders from my shares are not annoyed by this useless content.

Thank you!

**Comment by jpdillingham** [comment]
Thanks for raising this!  My intent was for the existing share filters to apply to directories too, but I'll double check that they do.

**Comment by khalimerot** [comment]
Maybe the error is in my side, i'm not good with regular expression.

I put : 
     - ^@eaDir
   
 in filters to try to avoid this folder.

**Comment by jpdillingham** [comment]
There is a bug that will leave the directories in there, but they'll be empty.  This is fixed in #668 which will be out in the canary in a few minutes.

I think the filter expression you want is just `@eadir`
