### ISSUE TITLE
Add a `DirectoryIsRelative` validation attribute, similar to `DirectoryExists` and add the attribute to the ContentPath option

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#684]
This should be as simple as checking [Path.IsPathRooted](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.ispathrooted?view=net-6.0) and failing validation if the result is `true`.

Once the attribute is added, add it to `ContentPath` in `Options`.

**Comment by pn04** [comment]
If this has not been picked up by anyone, can I work on it?

**Comment by jpdillingham** [comment]
In that case the default will be what's validated, so not necessary.  This is happening [here](https://github.com/slskd/slskd/blob/master/src/slskd/Program.cs#L333-L358); essentially the `Options` instance is materialized from all sources, bound to `OptionsAtStartup`, and then validated.

**Comment by jpdillingham** [comment]
Closed by #694.  Thanks!
