### ISSUE TITLE
Trying to open Uploads freezes browser tab. overloads CPU and RAM on server

### ISSUE THREAD

**Issue by moondownr** [slskd/slskd#685]
After fixing https://github.com/slskd/slskd/issues/683 I am flooded with a huge number of upload requests that (as far as I understand) were waiting for days.

Right now opening Uploads (on a remote PC) makes the page/tab freeze, Firefox complains that the page is slowing down the browser, meanwhile on the server CPU usage spikes to 100% and RAM usage rapidly grows both for slskd and for lighttpd. The page takes minutes to load anything and even then scrolling up or down causes it to hang again. After closing the tab, CPU usage stops, but RAM is not freed.

Can something be done? Restarting slskd doesn't help, as the upload history/requests persist.

**Comment by jpdillingham** [comment]
Unfortunately this is the next biggest shortcoming of the app right now after shares.  The design of the uploads screen isn't really suitable for pretty much anyone, and needs to be completely refactored.

The core issue is that transfers are never cleared unless you do it yourself, and the performance of the UI with a lot of files is lacking, so if you leave the app unattended long enough to cross this barrier you're stuck.

Right now the only thing you can do is delete `/data/transfers.db`, which will discard everything, including uploads and downloads, as well as anything queued or in progress.

I can add a feature that will let you purge completed transfers via the command line; I'll start on that shortly.

As always, I appreciate you raising this.

**Comment by jpdillingham** [comment]
Related to #650

**Comment by moondownr** [comment]
Thanks, deleting the *db did the trick.
I do forget about slskd for weeks sometimes (until I want to download something), but it was the first time it got so severe.

**Comment by cproensa** [comment]
> I can add a feature that will let you purge completed transfers via the command line;

+1 on this, a quick fix and this way could be added as a daily cron

**Comment by cproensa** [comment]
Is this command a valid workaround?
`sqlite3 transfers.db "update transfers set removed=1 where direction='Upload' and removed=0;"`

I have already ~100k uploads in that table, with removed=1. At what point is this table cleared?

**Comment by jpdillingham** [comment]
#700 introduces a new page under System that will allow you to clear transfers if they get 'stuck':

![image](https://user-images.githubusercontent.com/17145758/196458560-282836be-73fe-4f8d-b5a4-873f4b1154fa.png)

Alternatively there are two new REST endpoints:

* `DELETE /api/v0/transfers/downloads/all/completed`
* `DELETE /api/v0/transfers/uploads/all/completed`

If you want to set something up on a cron to handle this I suggest `curl`ing these two endpoints.  

Apologies for the delay on this!
