### ISSUE TITLE
Docker/Linux: Large number of stuck wget processes

### ISSUE THREAD

**Issue by wearejustvisiting** [slskd/slskd#702]
![image](https://user-images.githubusercontent.com/110168623/197330755-1c236715-1d99-40ff-9ce6-d737d0efa1ac.png)

under slskd, there are a number of `[wget] <defunct>` processes listed.

When logging in to Ubuntu, I see ` => There are 15 zombie processes.`

```
Docker Compose version v2.11.2
Server: Docker Engine - Community
 Engine:
  Version:          20.10.20
slskd 0.16.25.0-bd42906 (0.16.25.0-bd42906)
```

**Comment by jpdillingham** [comment]
Thanks for raising this.  The only thing `wget` is used for is the container [health check](https://github.com/slskd/slskd/blob/master/Dockerfile#L50), so this should be a simple fix.  I think the solution is to add [tini](https://github.com/krallin/tini)

**Comment by jpdillingham** [comment]
Actually now that I think through this a bit more, `tini` shouldn't have much to do with the health check, that's not really related to the application.  Maybe it will I guess; we'll wait and see.  It's not clear to me why wget is appearing as a child of slskd; it doesn't invoke it.

I think this might be my lack of understanding of how docker health checks work under the hood.  At any rate, let's see if tini solves it.  I'll create a release in a minute.

**Comment by jpdillingham** [comment]
More info [here](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/) it seems plausible that tini will fix this.
