### ISSUE TITLE
"Remove all" on Uploads page doesn't work, System/Data/Clear All does

### ISSUE THREAD

**Issue by moondownr** [slskd/slskd#761]
What the title says.

Back before the System option existed, I remember the Uploads button working. Now it just leads to the page becoming unresponsive, and on reload nothing happens.
The "Clear All" option in System/Data works and I can immediately go to Uploads and see them disappear in real time.

**Comment by jpdillingham** [comment]
Technically it works, but it works in a way that doesn't work well with large numbers of transfers.  Redesigning the uploads view is going to be my next priority.
