### ISSUE TITLE
Trouble accessing slskd

### ISSUE THREAD

**Issue by psonis** [slskd/slskd#837]
Running from Docker and all look fine but how do I access it from the web browser?
http://localhost:5000/ returns a 403 Forbidden message in the console.

<img width="798" alt="Screenshot 2023-01-08 at 14 46 25" src="https://user-images.githubusercontent.com/11035040/211196808-15b360b8-be04-481c-b7c2-46b19b8b4a95.png">

Thanks.

**Comment by jpdillingham** [comment]
It sounds like you might have forgotten to map port 5000.  Can you share the `docker` command you're using to start the container? It should look something like the ones documented [here](https://github.com/slskd/slskd/blob/master/docs/docker.md#running-slskd-in-docker)

**Comment by psonis** [comment]
> It sounds like you might have forgotten to map port 5000. Can you share the `docker` command you're using to start the container? It should look something like the ones documented [here](https://github.com/slskd/slskd/blob/master/docs/docker.md#running-slskd-in-docker)

This is the instructions I used as an example, and then I edited the slskd.yml to add the slsk credentials and enabled the    no_version_check: true flag.

Strangely I just tried it on a Windows 11 PC w/ WSL2 Docker and it worked! (The problem I mentioned above was on an Intel macOS 13.1 machine.)

**Comment by psonis** [comment]
Ok, look port like 5000 was the problem on my Mac, changed it (5005) and it works :)
Thanks.
