### ISSUE TITLE
ContentPath validation is broken

### ISSUE THREAD

**Issue by l5r** [slskd/slskd#846]
ContentPath is used relative to AppContext.BaseDirectory, but is validated to exist relative to the current directory (pwd).

Starting slskd in another directory is therefore impossible/botched.

**Comment by jpdillingham** [comment]
Thanks for reporting this, it is indeed a bug.  The behavior was changed in #687 but the options validation wasn't updated.

**Comment by jpdillingham** [comment]
This will be in the canary release in a few minutes, I'll create a release later today.

Thanks again!

**Comment by jpdillingham** [comment]
Released in [0.16.40](https://github.com/slskd/slskd/releases/tag/0.16.40)
