### ISSUE TITLE
Custom Username & Password for WebUI

### ISSUE THREAD

**Issue by driesvandamme** [slskd/slskd#86]
Allow us to change the Username & Password for the WebUI (Instead of fixed)
- Could be an environmental variable?

**Comment by jpdillingham** [comment]
Looks like you found the answer, but for anyone else that might stumble upon this, check out [Options.cs](https://github.com/slskd/slskd/blob/master/src/slskd/Options.cs) to see the available options.  The contents of this file also determine what is output when you run the app with `--help` and `--envars`.

At some point I'll update the readme and add documentation about what all of these do, but things are changing so quickly it will be wrong a lot.
