### ISSUE TITLE
Version check fails

### ISSUE THREAD

**Issue by Gladuin** [slskd/slskd#864]
I am using the latest binary release from the github releases section, 0.17.0.0+b55d705f, on Debian.

When I start slskd I get the error `Failed to check version: The input string '0+b55d705f' was not in a correct format.` .

I haven't configured anything else apart from my download and share dirs, and my username and password.

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I thought I fixed it in #849 but I guess not.  It may also be a regression.

**Comment by jpdillingham** [comment]
It's back in the latest version, this time as `The input string '0-f4dcc364' was not in a correct format`.

I'm ready to flip a table over this.  There are clearly nuances in the .NET versioning code that I don't fully understand.
