### ISSUE TITLE
[BUG] 0.17.1 | Not able to enter search results

### ISSUE THREAD

**Issue by EsEnZeT** [slskd/slskd#869]
After trying to enter search results user is immediately redirected to /searches

Version: 0.17.1.0-ff8d29cd

**Comment by jpoggi** [comment]
Hi,

Same here, I'm using version `0.17.1.0-ff8d29cd (0.17.1.0-ff8d29cd)`.

See ya.

**Comment by jpdillingham** [comment]
Thanks for reporting this.  I tested it last night when I was working on #868 and it was working but it's broken this morning 🤷 

0.17.2 will be out in a few minutes
