### ISSUE TITLE
How  to... umm... start?

### ISSUE THREAD

**Issue by bcsteeve** [slskd/slskd#871]
I'm not that much of a noob with self hosted apps lol, but I can't for the life of me figure out how to do ANYTHING with this one.  There's no user creation, nowhere to put in credentials, it just says disconnected with no way to connect.

Color me totally lost.

I've got it running... I've logged in with the default slskd/slskd username/password... now what?

**Comment by jpdillingham** [comment]
You'll need to configure a [username and password for the Soulseek network](https://github.com/slskd/slskd/blob/master/docs/config.md#username-and-password), then you're ready to start searching and downloading.  The [sources](https://github.com/slskd/slskd/blob/master/docs/config.md#sources) section describes the different options for setting the configuration.

**Comment by jpdillingham** [comment]
#875 updates the readme to include the port and login credentials for the web UI, and suggests that users turn remote configuration on.

Please let me know if anything is still unclear.
