### ISSUE TITLE
Unable to run behind a traefik proxy with latest port changes

### ISSUE THREAD

**Issue by tylerball** [slskd/slskd#873]
I use Traefik to proxy to a bunch of different services (plex, slskd, etc) on subdomains behind a single domain and https. Backend requests work fine through this setup (`https://soulseek.domain.com`, for example) but the fetch request used to initialize the frontend fails as port `5030` is not available through my proxy.

I believe [this change](https://github.com/slskd/slskd/pull/862/files#diff-6dbef4b0650fcc381da4a4b6808b5404b113af78eca7cde66364280bf9eff1cfL818) causes this to fail whereas before the port would be inferred from `window`, although I'm not sure exactly how this works.

**Comment by jpdillingham** [comment]
Thanks for raising this.  Injecting the port was a bit of a last minute change, let me go back and think that through some more.

**Comment by tylerball** [comment]
Actually, visiting the local server URL directly also doesn't work. I think the URL is malformed with that change:

<img width="556" alt="CleanShot 2023-02-03 at 16 10 45@2x" src="https://user-images.githubusercontent.com/73874/216711411-e5785488-afbf-47dc-9e4c-695dcc4c4771.png">

**Comment by jpdillingham** [comment]
Yeah this is totally broken.  Reverting in #874 and will create a new release shortly.

Thanks for the heads up.  I think I need to do some work to get parity between my dev/test environment and the real world, it works locally but it really shouldn't.

**Comment by jpdillingham** [comment]
No need for a new version; those changes were only active in the canary.

**Comment by jpdillingham** [comment]
Should be good now.  The root cause was a [careless typo](https://github.com/slskd/slskd/commit/5406cfcc457a738226945b40acce067c349579dc).  This port is injected into the frontend, but it's only used in development so there shouldn't be any change in behavior from previous versions there.

The canary is working on my instance at home, behind an IIS reverse proxy that changes port.

**Comment by tylerball** [comment]
Awesome, thanks! Pulled and verified that the latest canary works.
