### ISSUE TITLE
Documentation about the Distributed Network

### ISSUE THREAD

**Issue by UromPLAt** [slskd/slskd#878]
docs/config.md says:

_The distributed network should only be disabled if no files are being shared._

Are you sure that's true?
Even if you don't share files, doesn't slskd propagate search requests down to other SouldSeek clients? (children)

**Comment by jpdillingham** [comment]
When the distributed network is disabled the client won't request a list of parent candidates from the server and will therefore never connect to a parent, never receive searches, and won't be capable of forwarding searches.

Here's the relevant line in Soulseek.NET: https://github.com/jpdillingham/Soulseek.NET/blob/master/src/Network/DistributedConnectionManager.cs#L751

Additionally, the server uses an algorithm to match parents to children based on upload speed.  If you aren't sharing, you aren't uploading, and if you aren't uploading then your speed is zero, and theoretically no child would ever connect to you (my own conjecture, children with a speed of 0 may connect).

**Comment by jpdillingham** [comment]
Ideally nobody should disable the distributed network.  I use that flag when I'm developing so that I don't cause a bunch of extra traffic on the network with frequent reconnects (and it reduces the amount of debug logs by a lot).

**Comment by UromPLAt** [comment]
> Additionally, the server uses an algorithm to match parents to children based on upload speed. If you aren't sharing, you aren't uploading, and if you aren't uploading then your speed is zero, and theoretically no child would ever connect to you.

Hmm..if this is true, isn't it a design flaw of the network?
You have all these clients that are very capable of forwarding searches, but they won't.

I understand that the server code is proprietary so we can only guess how peers matching work?

**Comment by jpdillingham** [comment]
> Hmm..if this is true, isn't it a design flaw of the network?

I don't think so; there are a lot more parents than children.

> I understand that the server code is proprietary so we can only guess how peers matching work?

If you wanted to work out the formula you probably could with enough effort.  It's definitely based on the relative upload speeds of both parties, but I'm not sure what the ratios or difference percentage +/- are.  I trust that Nir has things tuned so they work well enough.

**Comment by jpdillingham** [comment]
Closing this since it seems like the questions have been answered, but feel free to re-open if you're curious about anything else!

**Comment by UromPLAt** [comment]
Thank you :)
