### ISSUE TITLE
Last canary image fails to start (docker-compose)

### ISSUE THREAD

**Issue by quorn23** [slskd/slskd#879]
The latest canary build 
`[0.17.3.65534-b98bf860](https://hub.docker.com/layers/slskd/slskd/0.17.3.65534-b98bf860/images/sha256-ef8b7af7816e82333da4fd98097bc1a6c510416c958adcc0d39670aad8bcb224?context=explore)`

fails to run with the error:

Failure processing application bundle.
Failed to create directory [/slskd/.net/] for extracting bundled files.

It just keeps looping repeating these two lines. Reversing to the canary before  `[0.17.3.65534-cf24c9ef](https://hub.docker.com/layers/slskd/slskd/0.17.3.65534-cf24c9ef/images/sha256-5a1ab3a7fa8b456b2649856f97630229fd90f73da6425abe2e9d121458926717?context=explore)` it starts up fine again. I see an older GHI #110 Merge #877 seems to have broken this again.

**Comment by jpdillingham** [comment]
Good timing, this was about 5 minutes away from being released!

Can you share your docker compose file?

**Comment by quorn23** [comment]
Ah darn, knew i forgot to add something.

```  soulseek:
    container_name: soulseek
    environment:
      - SLSKD_DOWNLOADS_DIR=${SLSKD_DOWNLOADS_DIR}
      - SLSKD_INCOMPLETE_DIR=${SLSKD_INCOMPLETE_DIR}
      - SLSKD_SHARED_DIR=${SLSKD_SHARED_DIR}
      - SLSKD_UPLOAD_SLOTS=${SLSKD_UPLOAD_SLOTS}
      - SLSKD_UPLOAD_SPEED_LIMIT=${SLSKD_UPLOAD_SPEED_LIMIT}
      - SLSKD_SLSK_USERNAME=${SLSKD_SLSK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_SLSK_LISTEN_PORT=${SLSKD_SLSK_LISTEN_PORT}
      - SLSKD_HTTP_PORT=${SLSKD_HTTP_PORT}
      - SLSKD_NO_AUTH=${SLSKD_NO_AUTH}
      - SLSKD_REMOTE_CONFIGURATION=${SLSKD_REMOTE_CONFIGURATION}
      - SLSKD_SLSK_NO_DNET=${SLSKD_SLSK_NO_DNET}
      - SLSKD_SLSK_DNET_NO_CHILDREN=${SLSKD_SLSK_DNET_NO_CHILDREN}
      - SLSKD_SLSK_DNET_CHILDREN=${SLSKD_SLSK_DNET_CHILDREN}
    image: ${SOULSEEK}
    network_mode: "service:qflood"
#   ports:
#     - ${PORT_SOULSEEK_5000}:5000
#     - ${PORT_SOULSEEK_43322}:43322
    restart: unless-stopped
    user: ${PUID}:${PGID}
    volumes:
      - ${DOCKERCONFDIR}/soulseek:/app
      - ${DOCKERDATADIR}:/data
    labels:
      - "org.hotio.pullio.notify=${PULLIO_NOTIFY}"
      - "org.hotio.pullio.update=${PULLIO_UPDATE}"
      - "org.hotio.pullio.discord.webhook=${PULLIO_DISCORD_WEBHOOK}"
      - "org.hotio.pullio.author.avatar=${AVATAR_SOULSEEK}"```

**Comment by jpdillingham** [comment]
#880 should fix this; I was able to reproduce it locally using both `docker run` and `docker compose up` and confirmed it was just a permissions issue when the container was started as a non-root user.

The new canary should be out in ~30 minutes and I'll test again before releasing to production.

@quorn23 if you could test with the new canary and confirm that this is fixed, I'd appreciate it!

**Comment by quorn23** [comment]
Switched back to the canary tag, fetched the new image, slskd is starting up fine, thanks for the fix!
