### ISSUE TITLE
Transfer aborted: the remote size of 0 does not match expected size

### ISSUE THREAD

**Issue by iamwoz** [slskd/slskd#896]
Some clients I connect to have a problem with multiple simultaneous downloads and report when I attempt:

**Transfer aborted: the remote size of 0 does not match expected size**

If I manually tick one file at a time and choose "Retry" then each file downloads fine.

Any chance of an option in the GUI that switches between one-by-one or parallel downloads?

Keep up the awesome work!

BTW: I have tried changing Global, Download, Slots to 1 - but get the same issue

**Comment by iamwoz** [comment]
closed because I think this is an issue with queuing at the remote end rather than simultaneous downloads (which SS doesn't do)

**Comment by jpdillingham** [comment]
Here's some background information on what causes this behavior:

Original issue: https://github.com/jpdillingham/Soulseek.NET/issues/710
Discussion that prompted the issue: https://github.com/jpdillingham/Soulseek.NET/discussions/708

Were the files you tried downloading over 2gb?
