### ISSUE TITLE
Add an option to schedule share re-scans periodically

### ISSUE THREAD

**Issue by 2ico** [slskd/slskd#900]
I get many error logs like the one below.
```
[22:25:23 INF] [UPLOAD REJECTED] user123 for downloads/Folder123\Mr. Oizo - Flat Beat [mp3clan].mp3: file not found
```
I can't figure out why because other files work, even in subfolders.

**Comment by jpdillingham** [comment]
This is almost certainly a bug in the remote client.  Are you seeing this with just this one user?

**Comment by 2ico** [comment]
It's happening with many users.

```
["UPLOAD REJECTED"] "user123" for "downloads/Folder123\Barbatuques - Baianá (Jack Back Remix).mp3": file not found
--
11:45:52 | WRN | Failed to resolve shared file "downloads/Folder123\Barbatuques - Baianá (Jack Back Remix).mp3
```

**Comment by Sakooooo** [comment]
happening to me too
```
[16:31:47 INF] [UPLOAD REQUESTED] misterplaceholder requested music\FIFTY FIFTY\The Beginning_ Cupid\02 Cupid (Twin version).flac
[16:31:47 WRN] Failed to resolve shared file music\FIFTY FIFTY\The Beginning_ Cupid\02 Cupid (Twin version).flac
[16:31:47 INF] [UPLOAD REJECTED] iamcooluser for music\FIFTY FIFTY\The Beginning_ Cupid\02 Cupid (Twin version).flac: file not found
```
he is using Seeker for android

**Comment by jpdillingham** [comment]
@2ico @Sakooooo can you confirm your slskd version and operating system (Windows, Linux) and/or whether you're using Docker?

**Comment by Sakooooo** [comment]
@jpdillingham im using linux with docker and it is version 0.17.8.0 (0.17.8.0+bb01112c) stable

**Comment by mathiascode** [comment]
Have you renamed any of your shared files recently (e.g. added/removed a symbol)? Are the file names/paths mentioned in the error messages the exact same as the current ones on your drive?

**Comment by Sakooooo** [comment]
weird thing slskd is starting to upload again after rebooting (?)
dont know if thats normal

**Comment by jpdillingham** [comment]
I thought I had left a comment but I must have gotten distracted and not clicked the button.

I mistakenly thought this log was generated when the remote client rejected an upload, and that's not correct (in my defense I wrote that code a long time ago 🙃)

What's happening here is that a remote client is asking for a file that doesn't exist.  It's highly unlikely that the remote client is making up a filename; it almost certainly got a search response or browsed your shares at some point in the past when the file was still there, and it moved or was deleted.

I do have a `todo` in the code that logs this message to force a re-scan of shares, but I don't think it's a good idea to actually force the scan.  Instead I can mark shares as "dirty" (needing to be re-scanned) to help users avoid this case.

Unfortunately this functionality isn't likely to improve.  I can add a filesystem "watch" to try and detect changes in real-time, but I know them to be buggy and they flat out won't work when using Docker, so it would be of limited use.

I can also add a setting to automatically rescan shares at a certain interval.

**Comment by mathiascode** [comment]
Even if your shares are always up to date, there will still be a few cases where someone is requesting an outdated file path, e.g. if there's a long queue, and they go offline for a few days before all files have finished downloading.

**Comment by Sakooooo** [comment]
that would be awesome! something like a cronjob would still be good :) as i do change my library frequently
