### ISSUE TITLE
API only mode

### ISSUE THREAD

**Issue by kernitus** [slskd/slskd#931]
Is there a way to run the application in API-only mode? Currently I am using the API exposed by `slskd` in another application I am writing but do not need the web frontend. It would be useful to only have the background daemon. 

I realise the API is not really stable nor documented, but I have been using it successfully after reverse-engineering it from the code, and think it has a lot of potential as a standalone software.

**Comment by jpdillingham** [comment]
Good idea!

I think this would be fairly straightforward to implement.  Some high level tasks:

* Add an option/flag to enable 'API only mode'
* During startup, if API only mode is enabled, don't include static file middleware
* Disable username/password login
* Ensure at least one API key is configured

I think that should do it but more stuff might pop up during implementation.  

@kernitus does this match your idea of an API only mode? (no static files/html served, no logging in etc)

**Comment by kernitus** [comment]
Yes, that sounds about right. Thank you for looking into this!

**Comment by hems** [comment]
I also ended up here because of my interest in using the API 👶 

Is there any documentation on help or any tips on how to interact with the app via API?

On my use case i would still keep the Web UI running but also issue some commands via API.

While checking the UI code i seen some of the commands are apparently issued via using [hubFactory](https://github.com/slskd/slskd/blob/master/src/web/src/lib/hubFactory.js) but i don't fully understand how this works as i have no experience with .NET....

In my case i would code the additional features i need using node.js so it might be the case i can use that same package `@microsoft/signalr` in order to remotely interact with the app?

**Comment by jpdillingham** [comment]
If you set the following option:

```yaml
web:
  feature:
    swagger: true
```

You can navigate to `/swagger` and get Swagger UI, which documents all of the API and provides examples.  You don't need to use SignalR, but you can if you want real-time interactivity.

Here's a screenshot:

![image](https://github.com/slskd/slskd/assets/17145758/9f8a999c-7487-47d6-bdb9-f2cb26c2c9db)

**Comment by hems** [comment]
> If you set the following option:
> 
> ```yaml
> web:
>   feature:
>     swagger: true
> ```
> 
> You can navigate to `/swagger` and get Swagger UI, which documents all of the API and provides examples. You don't need to use SignalR, but you can if you want real-time interactivity.

this is amazing!! <3

**Comment by phramusca** [comment]
This is just what I needed :)
However, I only receive 401 (unauthorized) even when calling http://localhost:5030/api/v0/session with my username and password
What authorization do I need to use ? It seems I need an API key ? Please help :)

**Comment by engineeredjoy** [comment]
Amazing work, and I too am very interested in the API. I (honestly) spent a while trying to make the auth work, and I figured I'd might not be the only one. So, there :-)
I'm running the docker container version, with the yaml config (extract) as:
``` web:
   port: 5030
#   https:
#     disabled: false
#     port: 5031
#     force: false
#     certificate:
#       pfx: ~
#       password: ~
#   url_base: /
#   content_path: wwwroot
#   logging: false
   authentication:
     disabled: false
     username: slskd
     password: slskd
#     jwt:
#       key: ~
#       ttl: 604800000
     api_keys:
       my_api_key:
         key: [some_long_string]
         role: readwrite # readonly, readwrite, administrator
         cidr: 0.0.0.0/0,::/0
```
It's a home setup with a nasty firewall, so a static key for my purpose would work fine. I also have the swagger activated, and it's neat. The only issue is the that testing in swagger does not allow for inputing the key (typically, the lock icon, which I dont have) And the request errors with a 401 and:
```
content-length: 0 
 date: Sun,05 Nov 2023 05:00:16 GMT 
 server: Kestrel 
 www-authenticate: Bearer 
```
Adding the API key I have defined gets me the same error:
```
curl -v -X GET "http://192.168.1.111:5030/api/v0/application" \
     -H "Authorization: Bearer some_long_string" \
     -H "Accept: application/json"
 ```
 
 I get `WWW-Authenticate: Bearer error="invalid_token"`.
 
 I *know* it is certainly something silly, but API access is a beautiful thing and maybe some other users got stuck on that, so...

**Comment by FaGuoMa** [comment]
I second that, but also am on the same project as the person above :-)

**Comment by FaGuoMa** [comment]
OK @jpdillingham I had in fact NOT looked enough. Commenting for anyone arriving on this thread: 
```
headers = {
        'X-API-Key': api_key,
        'Accept': 'application/json'
    }
```
[This merge page explains](https://github.com/slskd/slskd/pull/674)
