### ISSUE TITLE
Selecting Get Full Directory Contents removes the Download button when no new files are available

### ISSUE THREAD

**Issue by neofright** [slskd/slskd#948]
Steps to reproduce:

- Search for an album you want to download.
- Select all files in the album.
- Press 'Get Full Directory Contents'.
- If no new files are found, your file selection remains but the download button disappears.

**Comment by jpdillingham** [comment]
Weird! Thanks for reporting this, I'll try and reproduce it.  Should be a straightforward fix.

**Comment by neofright** [comment]
🎉
