### ISSUE TITLE
'Chats' view has too much vertical height and is scrolling the chat selection control out of sight

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#950]
Pretty straightforward reproduction; navigate to the view while at least one chat/private message is open.

This should be a simple fix involving CSS only.

**Comment by SandeepJoel** [comment]
@jpdillingham Can i pick this item ?

**Comment by jpdillingham** [comment]
Absolutely, please do!

**Comment by jpdillingham** [comment]
It looks like this is impacting all of the views.  I can scroll up and down on the search view when the content isn't filling the window, for example.  I think the container is probably 20px too high.
