### ISSUE TITLE
Failed to execute post-login actions

### ISSUE THREAD

**Issue by p3t3ypat3** [slskd/slskd#954]
Hello,

After connecting to the Soulseek server with my user login, the following error message appears in the log. It seems to prevent other users from seeing or downloading any of my shares.

Failed to execute post-login actions: System.ArgumentException: The username must not be a null or empty string, or one consisting of only whitespace (Parameter 'username') at Soulseek.SoulseekClient.GetUserStatisticsAsync(String username, Nullable`1 cancellationToken) at slskd.Application.RefreshUserStatistics(Boolean force) at slskd.Application.Client_LoggedIn(Object sender, EventArgs e)

**Comment by p3t3ypat3** [comment]
Many thanks. I restarted the docker container and it resolved the issue. 

You are right, I did initially start the application without the username, added it and then connected.

**Comment by jpdillingham** [comment]
Thanks for reporting back!  I made a code change so this won't negatively impact anyone else.
