### ISSUE TITLE
Completed, Errored are not retried

### ISSUE THREAD

**Issue by bpmb82** [slskd/slskd#958]
When downloading a lot of files from a user, most will get the 'Completed, Errored' status because only a limited amount of downloads are permitted at the same time. These are never retried (as far as I've seen) so I have to go in and press the 'Retry all errored' button manually for it to continue downloading.

Is there some option I've missed that causes slskd to retry these all the time? Or as soon as all queued downloads are done? I couldn't find any such option.

Running the latest docker container.

**Comment by bpmb82** [comment]
I just found that the download slots config option resolves this issue, below what I changed it to:

`global:
  upload:
    slots: 10
    speedLimit: 2147483647
  download:
    slots: 5
    speedLimit: 2147483647`

**Comment by jpdillingham** [comment]
I think this setting can help, but ultimately what it is doing is enqueueing download requests on your side.  This is generally not a problem, but if you try to download something from someone with a long wait queue, each locally enqueued download will enter their queue at the end.

To your original question, slskd doesn't do any automated retries of failed downloads.  It's ultimately something I want to add but I don't think it is on the roadmap anywhere.

**Comment by bpmb82** [comment]
Okay, so it's not ideal but at least for now it resolves the specific issue I was having. Should I create a feature request for the retry feature?

**Comment by jpdillingham** [comment]
Sure, I don't see an existing one.  Thanks!
