### ISSUE TITLE
scheduled clear of uploads

### ISSUE THREAD

**Issue by surtarso** [slskd/slskd#963]
Hi there, I share a really large amount of files and I'm wondering if there is a way to auto clear the uploads list since it gets way too big to handle on a daily basis. Maybe a way to skip the logging of uploads at all? I leave my instance on 24/7 and I don't really care what people are downloading from me really... I could skip logging entirely... but maybe a daily auto-clear of the list or something would help greatly users with 50k+ files...

Or maybe I am missing something about this that is already implemented? Please enlighten me.

ps: At the moment I'm just using a python script to automate the process in a very cheap way... It opens the browsers, logs in slskd and click the locations of 'uploads' and 'remove all succeeded'... but yeah, I dont wanna do that kkkk

**Comment by jpdillingham** [comment]
I started work on this this evening.  This will:

* Add configuration options to allow users to choose how long to keep succeeded, errored, and cancelled upload and downloads
* Add events to the system "clock" that fire on a regular interval to find upload/download records that are in a terminal state and where the age exceeds the configured value (in hours)
* Mark those records as removed, so they'll no longer be displayed in the UI (the records will remain in the database for historical purposes)

I had originally wanted to refactor the UI to make it possible to display all this data but in the meantime I think this will do.  I can add a way to view transfer history later.
