### ISSUE TITLE
Re-enable ARMv7 Docker images

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#987]
#986 removed arm/v7 from the multi-arch Docker build matrix because it was hanging and preventing the 0.19.0 release from going out.  Digging around on GitHub I've been able to confirm that this is an issue related to node and QEMU.  Some supporting info:

https://github.com/nodejs/docker-node/issues/1798
https://github.com/docker/build-push-action/issues/977

I'll keep an eye on this and re-enable the arm/v7 target when it has been resolved or an easy workaround is available.

If the lack of an ARMv7 Docker image is affecting you please comment or react to this issue.  If nobody does I'll probably leave it disabled.

**Comment by slook** [comment]
I need v7a.

**Comment by o-laptiy** [comment]
I'm using v7 version on my old raspberry pi, so having updates for it would be nice. 0.18.3.0 seems to be working just fine for me though.

**Comment by jpdillingham** [comment]
I will try re-enabling this over my holiday break.  I think if the underlying issue with node hasn't been fixed I should be able to target an earlier (working) build.

**Comment by jpdillingham** [comment]
The [0.19.2](https://github.com/slskd/slskd/releases/tag/0.19.2) release includes the arm v7 image.  Pinning the node image to v18 fixed it.

**Comment by jpdillingham** [comment]
I had to take this out again after failing all day to get a build out.  I'll add it back if it turns out this wasn't the problem.

**Comment by jpdillingham** [comment]
Re-enabled for both `latest` and `canary` tags in [0.19.5](https://github.com/slskd/slskd/releases/tag/0.19.5).

The publish of arm binaries is still fairly slow, but the big problem was building the frontend assets.  I've pinned that build to amd64 because the output is not architecture specific and we should be good to go.
