### ISSUE TITLE
Healthcheck failing and stuck at 'starting'

### ISSUE THREAD

**Issue by izzeho** [slskd/slskd#99]
Found I couldn't loadbalance through Traefik as it won't connect to containers with 'health: starting'.

From HEALTHCHECK it is attempting to use wget, which is not installed.

```
docker inspect --format "{{json .State.Health }}" slsk | jq
{
  "Status": "unhealthy",
  "FailingStreak": 11,
  "Log": [
    {
      "Start": "2021-06-16T17:04:10.903201276+10:00",
      "End": "2021-06-16T17:04:11.012057454+10:00",
      "ExitCode": 127,
      "Output": "/bin/sh: 1: wget: not found\n"
    },
}
```

**Comment by jpdillingham** [comment]
Thanks for reporting this, I noticed it was broke but hadn't given it a lot of thought.

The existing check was designed for Alpine and I never updated it (or thought to verify) after targeting buster-slim.
