### ISSUE TITLE
Disable logging to disk

### ISSUE THREAD

**Issue by onedr0p** [slskd/slskd#990]
Hi 👋🏼 
It would be awesome if there was a way to disable logging to disk completely. I have container logs from stdout pulled from [Vector](https://vector.dev/) and sent to [Loki](https://grafana.com/oss/loki/). It would be great to disable storing logs on disk.

Maybe setting the option `SLSKD_RETENTION_LOGS` to `0` or `-1` would be a good idea?

**Comment by jpdillingham** [comment]
Thanks for the suggestion!

**Comment by onedr0p** [comment]
Thanks for the quick turn around, I'm very impressed with the architecture and design choices in this project. Great work!
