### ISSUE TITLE
[feature request] Auto-join rooms on slskd startup

### ISSUE THREAD

**Issue by awsms** [slskd/slskd#999]
Would be cool to have an auto-connect feature for rooms, with persistent chat history

**Comment by Yousef40x** [comment]
Auto-join rooms on slskd startup

**Comment by jpdillingham** [comment]
Apologies, I intended to respond to this and it slipped my mind.

This feature is actually built in already (added in #185), but somehow I neglected to update the documentation when I added it. 

Here's the usage:

---

A configured list of chat rooms will now be automatically joined on connect.

The list can be specified via command line (e.g. `--rooms <room1> --rooms <room2>`), with the `SLSKD_ROOMS` environment variable (rooms separated by a semicolon), or in the yaml file as follows:

```yaml
rooms:
  - <room 1>
  - <room 2>
```

Additionally, when the client is disconnected, any rooms that were joined at the time of the disconnect are rejoined upon reconnect, as long as the app hasn't been restarted in between.
